{% set container_value = var('container') %}
{% set storage_account_value = var('storage_account') %}
{% set bootstrap_storage_location = var('bootstrap_storage_location') %}
{% set incremental_storage_location = var('incremental_storage_location') %}

{{ load_data_with_metadata(
    historical_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ bootstrap_storage_location ~"/MDKP.parquet",
    incremental_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_storage_location ~"/mdkp/",
    all_columns=[
		{"name": "mandt", "data_type": "STRING"},
		{"name": "dtart", "data_type": "STRING"},
		{"name": "matnr", "data_type": "STRING"},
		{"name": "plwrk", "data_type": "STRING"},
		{"name": "plscn", "data_type": "STRING"},
		{"name": "dtnum", "data_type": "STRING"},
		{"name": "dsdat", "data_type": "STRING"},
		{"name": "bdbkz", "data_type": "STRING"},
		{"name": "slkz1", "data_type": "STRING"},
		{"name": "slkz2", "data_type": "STRING"},
		{"name": "slkz3", "data_type": "STRING"},
		{"name": "slkz4", "data_type": "STRING"},
		{"name": "slkz5", "data_type": "STRING"},
		{"name": "slkz6", "data_type": "STRING"},
		{"name": "slkz7", "data_type": "STRING"},
		{"name": "slkz8", "data_type": "STRING"},
		{"name": "vrkz1", "data_type": "STRING"},
		{"name": "vrkz2", "data_type": "STRING"},
		{"name": "vrkz3", "data_type": "STRING"},
		{"name": "mtart", "data_type": "STRING"},
		{"name": "meins", "data_type": "STRING"},
		{"name": "disst", "data_type": "STRING"},
		{"name": "beskz", "data_type": "STRING"},
		{"name": "sobsl", "data_type": "STRING"},
		{"name": "sobes", "data_type": "STRING"},
		{"name": "wrk02", "data_type": "STRING"},
		{"name": "dismm", "data_type": "STRING"},
		{"name": "disvf", "data_type": "STRING"},
		{"name": "dispo", "data_type": "STRING"},
		{"name": "pldis", "data_type": "STRING"},
		{"name": "ekgrp", "data_type": "STRING"},
		{"name": "mtwzt", "data_type": "DECIMAL(13,3)"},
		{"name": "webaz", "data_type": "DECIMAL(13,3)"},
		{"name": "beazt", "data_type": "DECIMAL(13,3)"},
		{"name": "fixtr", "data_type": "STRING"},
		{"name": "mfhkz", "data_type": "STRING"},
		{"name": "disls", "data_type": "STRING"},
		{"name": "losvf", "data_type": "STRING"},
		{"name": "loskz", "data_type": "STRING"},
		{"name": "peraz", "data_type": "DECIMAL(13,3)"},
		{"name": "eisbe", "data_type": "DECIMAL(13,3)"},
		{"name": "minbe", "data_type": "DECIMAL(13,3)"},
		{"name": "hoebe", "data_type": "DECIMAL(13,3)"},
		{"name": "bstmi", "data_type": "DECIMAL(13,3)"},
		{"name": "bstma", "data_type": "DECIMAL(13,3)"},
		{"name": "bstfx", "data_type": "DECIMAL(13,3)"},
		{"name": "bstrf", "data_type": "DECIMAL(13,3)"},
		{"name": "sum01", "data_type": "DECIMAL(13,3)"},
		{"name": "sum02", "data_type": "DECIMAL(13,3)"},
		{"name": "sum03", "data_type": "DECIMAL(13,3)"},
		{"name": "sum04", "data_type": "DECIMAL(13,3)"},
		{"name": "sum05", "data_type": "DECIMAL(13,3)"},
		{"name": "negbs", "data_type": "DECIMAL(13,3)"},
		{"name": "msgid", "data_type": "STRING"},
		{"name": "msgar", "data_type": "STRING"},
		{"name": "msgnr", "data_type": "STRING"},
		{"name": "msgv1", "data_type": "STRING"},
		{"name": "msgv2", "data_type": "STRING"},
		{"name": "msgv3", "data_type": "STRING"},
		{"name": "msgv4", "data_type": "STRING"},
		{"name": "disgr", "data_type": "STRING"},
		{"name": "periv", "data_type": "STRING"},
		{"name": "mrppp", "data_type": "STRING"},
		{"name": "bdarf", "data_type": "DECIMAL(13,3)"},
		{"name": "lfrhy", "data_type": "STRING"},
		{"name": "rdprf", "data_type": "STRING"},
		{"name": "berw1", "data_type": "DECIMAL(13,3)"},
		{"name": "berw2", "data_type": "DECIMAL(13,3)"},
		{"name": "kzaus", "data_type": "STRING"},
		{"name": "ausdt", "data_type": "STRING"},
		{"name": "nfmat", "data_type": "STRING"},
		{"name": "ausz1", "data_type": "STRING"},
		{"name": "ausz2", "data_type": "STRING"},
		{"name": "ausz3", "data_type": "STRING"},
		{"name": "ausz4", "data_type": "STRING"},
		{"name": "ausz5", "data_type": "STRING"},
		{"name": "ausz6", "data_type": "STRING"},
		{"name": "ausz7", "data_type": "STRING"},
		{"name": "ausz8", "data_type": "STRING"},
		{"name": "beada", "data_type": "STRING"},
		{"name": "naukz", "data_type": "STRING"},
		{"name": "sauft", "data_type": "STRING"},
		{"name": "kzpromo", "data_type": "STRING"},
		{"name": "shflg", "data_type": "STRING"},
		{"name": "shzet", "data_type": "STRING"},
		{"name": "fabkz", "data_type": "STRING"},
		{"name": "mfxdt", "data_type": "STRING"},
		{"name": "bskfl", "data_type": "STRING"},
		{"name": "maabc", "data_type": "STRING"},
		{"name": "cflag", "data_type": "STRING"},
		{"name": "grrel", "data_type": "STRING"},
		{"name": "rwpro", "data_type": "STRING"},
		{"name": "shpro", "data_type": "STRING"},
		{"name": "ahdis", "data_type": "STRING"},
		{"name": "berw4", "data_type": "DECIMAL(13,3)"},
		{"name": "badon", "data_type": "STRING"},
		{"name": "sgt_statc", "data_type": "STRING"},
		{"name": "hanaon", "data_type": "STRING"},
		{"name": "tas_rp_change_date", "data_type": "TIMESTAMP"},
		{"name": "tas_rp_opcode", "data_type": "INT"}
    ],
    composite_keys=["mandt","dtart","matnr","plwrk","plscn"],
    transformation_column="tas_rp_opcode",
    transformation_map={"D": 0, "I": 1, "U": 2}
) }}