{% set container_value = var('container') %}
{% set storage_account_value = var('storage_account') %}
{% set bootstrap_storage_location = var('bootstrap_storage_location') %}
{% set incremental_storage_location = var('incremental_storage_location') %}

{{ load_data_with_metadata(
    historical_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ bootstrap_storage_location ~"/rseg.parquet",
    incremental_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_storage_location ~"/rseg/",
    all_columns=[
		{"name": "mandt", "data_type": "STRING"},
		{"name": "belnr", "data_type": "STRING"},
		{"name": "gjahr", "data_type": "STRING"},
		{"name": "buzei", "data_type": "STRING"},
		{"name": "ebeln", "data_type": "STRING"},
		{"name": "ebelp", "data_type": "STRING"},
		{"name": "zekkn", "data_type": "STRING"},
		{"name": "matnr", "data_type": "STRING"},
		{"name": "bwkey", "data_type": "STRING"},
		{"name": "bwtar", "data_type": "STRING"},
		{"name": "bukrs", "data_type": "STRING"},
		{"name": "werks", "data_type": "STRING"},
		{"name": "wrbtr", "data_type": "DECIMAL(13,3)"},
		{"name": "shkzg", "data_type": "STRING"},
		{"name": "mwskz", "data_type": "STRING"},
		{"name": "txjcd", "data_type": "STRING"},
		{"name": "menge", "data_type": "DECIMAL(13,3)"},
		{"name": "bstme", "data_type": "STRING"},
		{"name": "bpmng", "data_type": "DECIMAL(13,3)"},
		{"name": "bprme", "data_type": "STRING"},
		{"name": "lbkum", "data_type": "DECIMAL(13,3)"},
		{"name": "vrkum", "data_type": "DECIMAL(13,3)"},
		{"name": "meins", "data_type": "STRING"},
		{"name": "pstyp", "data_type": "STRING"},
		{"name": "knttp", "data_type": "STRING"},
		{"name": "bklas", "data_type": "STRING"},
		{"name": "erekz", "data_type": "STRING"},
		{"name": "exkbe", "data_type": "STRING"},
		{"name": "xekbz", "data_type": "STRING"},
		{"name": "tbtkz", "data_type": "STRING"},
		{"name": "spgrp", "data_type": "STRING"},
		{"name": "spgrm", "data_type": "STRING"},
		{"name": "spgrt", "data_type": "STRING"},
		{"name": "spgrg", "data_type": "STRING"},
		{"name": "spgrv", "data_type": "STRING"},
		{"name": "spgrq", "data_type": "STRING"},
		{"name": "spgrs", "data_type": "STRING"},
		{"name": "spgrc", "data_type": "STRING"},
		{"name": "spgrext", "data_type": "STRING"},
		{"name": "bustw", "data_type": "STRING"},
		{"name": "xblnr", "data_type": "STRING"},
		{"name": "xrueb", "data_type": "STRING"},
		{"name": "bnkan", "data_type": "DECIMAL(13,3)"},
		{"name": "kschl", "data_type": "STRING"},
		{"name": "salk3", "data_type": "DECIMAL(13,3)"},
		{"name": "vmsal", "data_type": "DECIMAL(13,3)"},
		{"name": "xlifo", "data_type": "STRING"},
		{"name": "lfbnr", "data_type": "STRING"},
		{"name": "lfgja", "data_type": "STRING"},
		{"name": "lfpos", "data_type": "STRING"},
		{"name": "matbf", "data_type": "STRING"},
		{"name": "rbmng", "data_type": "DECIMAL(13,3)"},
		{"name": "bprbm", "data_type": "DECIMAL(13,3)"},
		{"name": "rbwwr", "data_type": "DECIMAL(13,3)"},
		{"name": "lfehl", "data_type": "STRING"},
		{"name": "gricd", "data_type": "STRING"},
		{"name": "grirg", "data_type": "STRING"},
		{"name": "gityp", "data_type": "STRING"},
		{"name": "packno", "data_type": "STRING"},
		{"name": "introw", "data_type": "STRING"},
		{"name": "sgtxt", "data_type": "STRING"},
		{"name": "xskrl", "data_type": "STRING"},
		{"name": "kzmek", "data_type": "STRING"},
		{"name": "mrmok", "data_type": "STRING"},
		{"name": "stunr", "data_type": "STRING"},
		{"name": "zaehk", "data_type": "STRING"},
		{"name": "stock_posting", "data_type": "DECIMAL(13,3)"},
		{"name": "stock_posting_pp", "data_type": "DECIMAL(13,3)"},
		{"name": "stock_posting_py", "data_type": "DECIMAL(13,3)"},
		{"name": "werec", "data_type": "STRING"},
		{"name": "lifnr", "data_type": "STRING"},
		{"name": "frbnr", "data_type": "STRING"},
		{"name": "xhistma", "data_type": "STRING"},
		{"name": "complaint_reason", "data_type": "STRING"},
		{"name": "retamt_fc", "data_type": "DECIMAL(13,3)"},
		{"name": "retpc", "data_type": "DECIMAL(13,3)"},
		{"name": "retduedt", "data_type": "STRING"},
		{"name": "xrettaxnet", "data_type": "STRING"},
		{"name": "re_account", "data_type": "STRING"},
		{"name": "erp_contract_id", "data_type": "STRING"},
		{"name": "erp_contract_itm", "data_type": "STRING"},
		{"name": "srm_contract_id", "data_type": "STRING"},
		{"name": "srm_contract_itm", "data_type": "STRING"},
		{"name": "cont_pstyp", "data_type": "STRING"},
		{"name": "srvmapkey", "data_type": "STRING"},
		{"name": "charg", "data_type": "STRING"},
		{"name": "inv_itm_origin", "data_type": "STRING"},
		{"name": "invrel", "data_type": "STRING"},
		{"name": "xdinv", "data_type": "STRING"},
		{"name": "diff_amount", "data_type": "DECIMAL(13,3)"},
		{"name": "xcprf", "data_type": "STRING"},
		{"name": "fsh_season_year", "data_type": "STRING"},
		{"name": "fsh_season", "data_type": "STRING"},
		{"name": "fsh_collection", "data_type": "STRING"},
		{"name": "fsh_theme", "data_type": "STRING"},
		{"name": "hsn_sac", "data_type": "STRING"},
		{"name": "customs_val", "data_type": "DECIMAL(13,3)"},
		{"name": "licno", "data_type": "STRING"},
		{"name": "zeile", "data_type": "STRING"},
		{"name": "sgt_scat", "data_type": "STRING"},
		{"name": "wrf_charstc1", "data_type": "STRING"},
		{"name": "wrf_charstc2", "data_type": "STRING"},
		{"name": "wrf_charstc3", "data_type": "STRING"},
		{"name": "tas_rp_change_date", "data_type": "TIMESTAMP"},
		{"name": "tas_rp_opcode", "data_type": "INT"}
    ],
    composite_keys=["mandt","belnr","gjahr","buzei"],
    transformation_column="tas_rp_opcode",
    transformation_map={"D": 0, "I": 1, "U": 2}
) }}