{% set container_value1 = var('container_1') %}
{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}


{{ load_tms_macro(
    source_path="abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Load_RP_RS_Payable_Rate",
    merge_col = 'loadid',
	files_format = "csv",
    delimiter = '|',
    all_columns = [
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "loadid", "data_type": "STRING"},
        {"name": "planid", "data_type": "STRING"},
        {"name": "stepid", "data_type": "STRING"},
        {"name": "payablerateid", "data_type": "STRING"},
        {"name": "payablerateheaderid", "data_type": "STRING"},
        {"name": "chargecodeid", "data_type": "STRING"},
        {"name": "chargetype", "data_type": "STRING"},
        {"name": "id", "data_type": "STRING"},
        {"name": "chargeorigin", "data_type": "STRING"},
        {"name": "chargeorigin_id", "data_type": "STRING"},
        {"name": "stopid", "data_type": "STRING"},
        {"name": "shipperdescription", "data_type": "STRING"},
        {"name": "basistype", "data_type": "STRING"},
        {"name": "quantity", "data_type": "STRING"},
        {"name": "rate", "data_type": "STRING"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "grossamt", "data_type": "STRING"},
        {"name": "grossamt_currencycode", "data_type": "STRING"},
        {"name": "discountapplied", "data_type": "STRING"},
        {"name": "discountrate", "data_type": "STRING"},
        {"name": "discountrate_currencycode", "data_type": "STRING"},
        {"name": "discountamt", "data_type": "STRING"},
        {"name": "discountamt_currencycode", "data_type": "STRING"},
        {"name": "tenderamt", "data_type": "STRING"},
        {"name": "tenderamt_currencycode", "data_type": "STRING"},
        {"name": "nettotal", "data_type": "STRING"},
        {"name": "nettotal_currencycode", "data_type": "STRING"},
        {"name": "freightclass", "data_type": "STRING"},
        {"name": "freightratedas", "data_type": "STRING"},
        {"name": "sequencenum", "data_type": "STRING"},
        {"name": "container", "data_type": "STRING"},
        {"name": "container_id", "data_type": "STRING"},
        {"name": "chargecodegroup", "data_type": "STRING"},
        {"name": "chargecodegroup_id", "data_type": "STRING"},
        {"name": "chargecodecategory", "data_type": "STRING"},
        {"name": "chargecodecategory_id", "data_type": "STRING"},
        {"name": "contracttype", "data_type": "STRING"},
        {"name": "contracttype_id", "data_type": "STRING"},
    ],
    staging_columns = [
        "a.payablerateid","a.payablerateheaderid","a.chargecodeid",
        "a.chargetype",
        "a.id",
        "a.chargeorigin",
        "a.chargeorigin_id",
        "a.stopid",
        "a.shipperdescription",
        "a.basistype",
        "a.quantity",
        "a.rate",
        "a.currencycode",
        "a.grossamt",
        "a.grossamt_currencycode",
        "a.discountapplied",
        "a.discountrate",
        "a.discountrate_currencycode",
        "a.discountamt",
        "a.discountamt_currencycode",
        "a.tenderamt",
        "a.tenderamt_currencycode",
        "a.nettotal",
        "a.nettotal_currencycode",
        "a.freightclass",
        "a.freightratedas",
        "a.sequencenum",
        "a.container",
        "a.container_id",
        "a.chargecodegroup",
        "a.chargecodegroup_id",
        "a.chargecodecategory",
        "a.chargecodecategory_id",
        "a.contracttype",
        "a.contracttype_id",
        "a.stepid",
        "a.planid",
        "a.loadid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName AS SourceFileName"
    ],
    target_columns = [
        "CAST(a.payablerateid AS INT) AS payablerateid",
        "CAST(a.payablerateheaderid AS INT) AS payablerateheaderid",
        "CAST(a.chargecodeid AS STRING) AS chargecodeid",
        "CAST(a.chargetype AS STRING) AS chargetype",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.chargeorigin AS STRING) AS chargeorigin",
        "CAST(a.chargeorigin_id AS STRING) AS chargeorigin_id",
        "CAST(a.stopid AS INT) AS stopid",
        "CAST(a.shipperdescription AS STRING) AS shipperdescription",
        "CAST(a.basistype AS STRING) AS basistype",
        "CAST(a.quantity AS DECIMAL(16,2)) AS quantity",
        "CAST(a.rate AS STRING) AS rate",
        "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.grossamt AS STRING) AS grossamt",
        "CAST(a.grossamt_currencycode AS STRING) AS grossamt_currencycode",
        "CAST(a.discountapplied AS INT) AS discountapplied",
        "CAST(a.discountrate AS STRING) AS discountrate",
        "CAST(a.discountrate_currencycode AS STRING) AS discountrate_currencycode",
        "CAST(a.discountamt AS STRING) AS discountamt",
        "CAST(a.discountamt_currencycode AS STRING) AS discountamt_currencycode",
        "CAST(a.tenderamt AS STRING) AS tenderamt",
        "CAST(a.tenderamt_currencycode AS STRING) AS tenderamt_currencycode",
        "CAST(a.nettotal AS STRING) AS nettotal",
        "CAST(a.nettotal_currencycode AS STRING) AS nettotal_currencycode",
        "CAST(a.freightclass AS STRING) AS freightclass",
        "CAST(a.freightratedas AS STRING) AS freightratedas",
        "CAST(a.sequencenum AS INT) AS sequencenum",
        "CAST(a.container AS STRING) AS container",
        "CAST(a.container_id AS STRING) AS container_id",
        "CAST(a.chargecodegroup AS STRING) AS chargecodegroup",
        "CAST(a.chargecodegroup_id AS STRING) AS chargecodegroup_id",
        "CAST(a.chargecodecategory AS STRING) AS chargecodecategory",
        "CAST(a.chargecodecategory_id AS STRING) AS chargecodecategory_id",
        "CAST(a.contracttype AS STRING) AS contracttype",
        "CAST(a.contracttype_id AS STRING) AS contracttype_id",
        "CAST(a.stepid AS INT) AS stepid",
        "CAST(a.planid AS INT) AS planid",
        "CAST(a.loadid AS INT) AS loadid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date"
    ]
) }}