{% set container_value1 = var('container_1') %}
{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}


{{ load_tms_macro(
    source_path="abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Shipment_Shipment_Leg",
	merge_col = 'shipmentid',
    files_format = "csv",
    delimiter = '|',
    all_columns = [
        {"name": "location_name", "data_type": "STRING"},
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "shipmentid", "data_type": "INTEGER"},
        {"name": "shipmentlegid", "data_type": "INTEGER"},
        {"name": "status", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "sequencenum", "data_type": "INTEGER"},
        {"name": "distance", "data_type": "INTEGER"},
        {"name": "unit", "data_type": "STRING"},
        {"name": "loadid", "data_type": "INTEGER"},
        {"name": "pickloaddetailid", "data_type": "INTEGER"},
        {"name": "ref", "data_type": "STRING"},
        {"name": "name", "data_type": "STRING"},
        {"name": "address1", "data_type": "STRING"},
        {"name": "address2", "data_type": "STRING"},
        {"name": "address3", "data_type": "STRING"},
        {"name": "city", "data_type": "STRING"},
        {"name": "state", "data_type": "STRING"},
        {"name": "zip", "data_type": "STRING"},
        {"name": "country", "data_type": "STRING"},
        {"name": "timezone", "data_type": "STRING"},
        {"name": "dst", "data_type": "INTEGER"},
        {"name": "timezoneid", "data_type": "STRING"},
        {"name": "contactname", "data_type": "STRING"},
        {"name": "contactphonenum", "data_type": "STRING"},
        {"name": "contactphoneext", "data_type": "INTEGER"},
        {"name": "apptcontactname", "data_type": "STRING"},
        {"name": "apptcontactphonenum", "data_type": "STRING"},
        {"name": "apptcontactphoneext", "data_type": "STRING"},
        {"name": "poolpoint", "data_type": "INTEGER"},
        {"name": "previousdroplotshipmentlegid", "data_type": "STRING"},
        {"name": "droploaddetailid", "data_type": "INTEGER"},
        {"name": "location_ref", "data_type": "STRING"},
        {"name": "location_address1", "data_type": "STRING"},
        {"name": "location_address2", "data_type": "STRING"},
        {"name": "location_address3", "data_type": "STRING"},
        {"name": "location_city", "data_type": "STRING"},
        {"name": "location_state", "data_type": "STRING"},
        {"name": "location_zip", "data_type": "STRING"},
        {"name": "location_country", "data_type": "STRING"},
        {"name": "location_timezone", "data_type": "STRING"},
        {"name": "location_dst", "data_type": "INTEGER"},
        {"name": "location_timezoneid", "data_type": "STRING"},
        {"name": "location_contactname", "data_type": "STRING"},
        {"name": "location_contactphonenum", "data_type": "STRING"},
        {"name": "location_contactphoneext", "data_type": "INTEGER"},
        {"name": "location_apptcontactname", "data_type": "STRING"},
        {"name": "location_apptcontactphonenum", "data_type": "STRING"},
        {"name": "location_apptcontactphoneext", "data_type": "INTEGER"},
        {"name": "location_poolpoint", "data_type": "INTEGER"},
        {"name": "nextdroplotshipmentlegid", "data_type": "STRING"},
        {"name": "whseloadingorder", "data_type": "INTEGER"},
        {"name": "billableallocation", "data_type": "STRING"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "payableallocation", "data_type": "DOUBLE"},
        {"name": "payableallocation_currencycode", "data_type": "STRING"},
        {"name": "pickwindowstartdate", "data_type": "TIMESTAMP"},
        {"name": "pickwindowenddate", "data_type": "TIMESTAMP"},
        {"name": "originalpickstartdate", "data_type": "STRING"},
        {"name": "originalpickenddate", "data_type": "STRING"},
        {"name": "dropwindowstartdate", "data_type": "TIMESTAMP"},
        {"name": "dropwindowenddate", "data_type": "TIMESTAMP"},
        {"name": "originaldropstartdate", "data_type": "STRING"},
        {"name": "originaldropenddate", "data_type": "STRING"},
        {"name": "estltlrate", "data_type": "STRING"},
        {"name": "estltlrate_currencycode", "data_type": "STRING"},
        {"name": "tmsplanningability", "data_type": "STRING"},
        {"name": "tmsplanningability_id", "data_type": "INTEGER"},
        {"name": "shipcode", "data_type": "STRING"},
        {"name": "shipcode_id", "data_type": "STRING"},
        {"name": "edicode", "data_type": "STRING"},
        {"name": "goodsissueddate", "data_type": "STRING"},
        {"name": "goodsreceiveddate", "data_type": "STRING"},
        {"name": "firstleg", "data_type": "INTEGER"},
        {"name": "lastleg", "data_type": "INTEGER"}
    ],
    staging_columns = [
        "a.shipmentlegid", "a.status", "a.id", "a.sequencenum",
        "a.distance", "a.unit", "a.loadid", "a.pickloaddetailid",
        "a.ref", "a.name", "a.address1", "a.address2", "a.address3",
        "a.city", "a.state", "a.zip", "a.country", "a.timezone",
        "a.dst", "a.timezoneid", "a.contactname", "a.contactphonenum",
        "a.contactphoneext", "a.apptcontactname", "a.apptcontactphonenum",
        "a.apptcontactphoneext", "a.poolpoint", "a.previousdroplotshipmentlegid",
        "a.droploaddetailid", "a.location_ref", "a.location_name",
        "a.location_address1", "a.location_address2", "a.location_address3",
        "a.location_city", "a.location_state", "a.location_zip",
        "a.location_country", "a.location_timezone", "a.location_dst",
        "a.location_timezoneid", "a.location_contactname", "a.location_contactphonenum",
        "a.location_contactphoneext", "a.location_apptcontactname",
        "a.location_apptcontactphonenum", "a.location_apptcontactphoneext",
        "a.location_poolpoint", "a.nextdroplotshipmentlegid",
        "a.whseloadingorder", "a.billableallocation", "a.currencycode",
        "a.payableallocation", "a.payableallocation_currencycode",
        "a.pickwindowstartdate", "a.pickwindowenddate", "a.originalpickstartdate",
        "a.originalpickenddate", "a.dropwindowstartdate", "a.dropwindowenddate",
        "a.originaldropstartdate", "a.originaldropenddate", "a.estltlrate",
        "a.estltlrate_currencycode", "a.tmsplanningability", "a.tmsplanningability_id",
        "a.shipcode", "a.shipcode_id", "a.edicode", "a.goodsissueddate",
        "a.goodsreceiveddate", "a.firstleg", "a.lastleg",
        "TRIM(CAST(a.shipmentid AS CHAR(30))) AS shipmentid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName AS SourceFileName"
    ],
    target_columns = [
        "CAST(a.shipmentlegid AS INT) AS shipmentlegid", "CAST(a.status AS STRING) AS status",
        "CAST(a.id AS STRING) AS id", "CAST(a.sequencenum AS INT) AS sequencenum",
        "CAST(a.distance AS STRING) AS distance", "CAST(a.unit AS STRING) AS unit",
        "CAST(a.loadid AS INT) AS loadid", "CAST(a.pickloaddetailid AS INT) AS pickloaddetailid",
        "CAST(a.ref AS STRING) AS ref", "CAST(a.name AS STRING) AS name",
        "CAST(a.address1 AS STRING) AS address1", "CAST(a.address2 AS STRING) AS address2",
        "CAST(a.address3 AS STRING) AS address3", "CAST(a.city AS STRING) AS city",
        "CAST(a.state AS STRING) AS state", "CAST(a.zip AS STRING) AS zip",
        "CAST(a.country AS STRING) AS country", "CAST(a.timezone AS STRING) AS timezone",
        "CAST(a.dst AS INT) AS dst", "CAST(a.timezoneid AS STRING) AS timezoneid",
        "CAST(a.contactname AS STRING) AS contactname", "CAST(a.contactphonenum AS STRING) AS contactphonenum",
        "CAST(a.contactphoneext AS STRING) AS contactphoneext", "CAST(a.apptcontactname AS STRING) AS apptcontactname",
        "CAST(a.apptcontactphonenum AS STRING) AS apptcontactphonenum", "CAST(a.apptcontactphoneext AS STRING) AS apptcontactphoneext",
        "CAST(a.poolpoint AS INT) AS poolpoint", "CAST(a.previousdroplotshipmentlegid AS INT) AS previousdroplotshipmentlegid",
        "CAST(a.droploaddetailid AS INT) AS droploaddetailid", "CAST(a.location_ref AS STRING) AS location_ref",
        "CAST(a.location_name AS STRING) AS location_name", "CAST(a.location_address1 AS STRING) AS location_address1",
        "CAST(a.location_address2 AS STRING) AS location_address2", "CAST(a.location_address3 AS STRING) AS location_address3",
        "CAST(a.location_city AS STRING) AS location_city", "CAST(a.location_state AS STRING) AS location_state",
        "CAST(a.location_zip AS STRING) AS location_zip", "CAST(a.location_country AS STRING) AS location_country",
        "CAST(a.location_timezone AS STRING) AS location_timezone", "CAST(a.location_dst AS INT) AS location_dst",
        "CAST(a.location_timezoneid AS STRING) AS location_timezoneid", "CAST(a.location_contactname AS STRING) AS location_contactname",
        "CAST(a.location_contactphonenum AS STRING) AS location_contactphonenum", "CAST(a.location_contactphoneext AS STRING) AS location_contactphoneext",
        "CAST(a.location_apptcontactname AS STRING) AS location_apptcontactname", "CAST(a.location_apptcontactphonenum AS STRING) AS location_apptcontactphonenum",
        "CAST(a.location_apptcontactphoneext AS STRING) AS location_apptcontactphoneext", "CAST(a.location_poolpoint AS INT) AS location_poolpoint",
        "CAST(a.nextdroplotshipmentlegid AS INT) AS nextdroplotshipmentlegid", "CAST(a.whseloadingorder AS INT) AS whseloadingorder",
        "CAST(a.billableallocation AS STRING) AS billableallocation", "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.payableallocation AS STRING) AS payableallocation", "CAST(a.payableallocation_currencycode AS STRING) AS payableallocation_currencycode",
        "CAST(a.pickwindowstartdate AS STRING) AS pickwindowstartdate", "CAST(a.pickwindowenddate AS STRING) AS pickwindowenddate",
        "CAST(a.originalpickstartdate AS STRING) AS originalpickstartdate", "CAST(a.originalpickenddate AS STRING) AS originalpickenddate",
        "CAST(a.dropwindowstartdate AS STRING) AS dropwindowstartdate", "CAST(a.dropwindowenddate AS STRING) AS dropwindowenddate",
        "CAST(a.originaldropstartdate AS STRING) AS originaldropstartdate", "CAST(a.originaldropenddate AS STRING) AS originaldropenddate",
        "CAST(a.estltlrate AS STRING) AS estltlrate", "CAST(a.estltlrate_currencycode AS STRING) AS estltlrate_currencycode",
        "CAST(a.tmsplanningability AS STRING) AS tmsplanningability", "CAST(a.tmsplanningability_id AS STRING) AS tmsplanningability_id",
        "CAST(a.shipcode AS STRING) AS shipcode", "CAST(a.shipcode_id AS STRING) AS shipcode_id",
        "CAST(a.edicode AS STRING) AS edicode", "CAST(a.goodsissueddate AS STRING) AS goodsissueddate",
        "CAST(a.goodsreceiveddate AS STRING) AS goodsreceiveddate", "CAST(a.firstleg AS INT) AS firstleg",
        "CAST(a.lastleg AS INT) AS lastleg",
        "CAST(a.shipmentid AS INT) AS shipmentid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date"
    ]
) }}