{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}

{{
  load_tms_macro(
    source_path = "abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Shipment",
    merge_col = 'shipmentid',
	  files_format = "csv",
	  delimiter = '|',
    all_columns = [
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "o_comments", "data_type": "STRING"},
        {"name": "customer", "data_type": "STRING"},
        {"name": "shipmentid", "data_type": "INTEGER"},
        {"name": "integrationkey", "data_type": "LONG"},
        {"name": "ref", "data_type": "LONG"},
        {"name": "tmsplanningability", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "status", "data_type": "STRING"},
        {"name": "status_id", "data_type": "INTEGER"},
        {"name": "type", "data_type": "STRING"},
        {"name": "type_id", "data_type": "INTEGER"},
        {"name": "shipperaccountcode", "data_type": "STRING"},
        {"name": "division", "data_type": "STRING"},
        {"name": "division_id", "data_type": "INTEGER"},
        {"name": "ordergroup", "data_type": "STRING"},
        {"name": "ordergroup_id", "data_type": "INTEGER"},
        {"name": "company", "data_type": "STRING"},
        {"name": "company_id", "data_type": "INTEGER"},
        {"name": "contact_id", "data_type": "INTEGER"},
        {"name": "firstname", "data_type": "STRING"},
        {"name": "lastname", "data_type": "STRING"},
        {"name": "username", "data_type": "STRING"},
        {"name": "ordercontact_contact_id", "data_type": "INTEGER"},
        {"name": "contact_firstname", "data_type": "STRING"},
        {"name": "contact_lastname", "data_type": "STRING"},
        {"name": "contact_username", "data_type": "STRING"},
        {"name": "createdate", "data_type": "TIMESTAMP"},
        {"name": "directioncatgid", "data_type": "STRING"},
        {"name": "distance", "data_type": "INTEGER"},
        {"name": "unit", "data_type": "STRING"},
        {"name": "weight", "data_type": "DOUBLE"},
        {"name": "weight_unit", "data_type": "STRING"},
        {"name": "volume", "data_type": "DOUBLE"},
        {"name": "volume_unit", "data_type": "STRING"},
        {"name": "cases", "data_type": "INTEGER"},
        {"name": "pallets", "data_type": "DOUBLE"},
        {"name": "pieces", "data_type": "INTEGER"},
        {"name": "hazmat", "data_type": "INTEGER"},
        {"name": "palletexchange", "data_type": "INTEGER"},
        {"name": "billabletotal", "data_type": "STRING"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "billablecalcdate", "data_type": "STRING"},
        {"name": "freightbillableparty", "data_type": "STRING"},
        {"name": "freightbillableparty_id", "data_type": "STRING"},
        {"name": "payableallocation", "data_type": "DOUBLE"},
        {"name": "payableallocation_currencycode", "data_type": "STRING"},
        {"name": "podreceived", "data_type": "STRING"},
        {"name": "payrequirement", "data_type": "STRING"},
        {"name": "payrequirement_id", "data_type": "INTEGER"},
        {"name": "omsorderid", "data_type": "INTEGER"},
        {"name": "omsorderlegid", "data_type": "INTEGER"},
        {"name": "parentcustomer", "data_type": "STRING"},
        {"name": "parentcustomer_id", "data_type": "STRING"},
        {"name": "parentcustomer_ref", "data_type": "STRING"},
        {"name": "customer_id", "data_type": "INTEGER"},
        {"name": "customer_ref", "data_type": "INTEGER"},
        {"name": "supplier", "data_type": "STRING"},
        {"name": "supplier_id", "data_type": "STRING"},
        {"name": "supplier_ref", "data_type": "STRING"},
        {"name": "salesgroup", "data_type": "STRING"},
        {"name": "salesgroup_id", "data_type": "INTEGER"},
        {"name": "methodofpayment", "data_type": "STRING"},
        {"name": "billableid", "data_type": "STRING"},
        {"name": "trailertype", "data_type": "STRING"},
        {"name": "nettotal", "data_type": "STRING"},
        {"name": "nettotal_currencycode", "data_type": "STRING"},
        {"name": "ratemthd", "data_type": "STRING"},
        {"name": "billablemethod", "data_type": "STRING"},
        {"name": "billablemethod_id", "data_type": "STRING"},
        {"name": "valuation", "data_type": "DOUBLE"},
        {"name": "salesordernum", "data_type": "STRING"},
        {"name": "shipwithref", "data_type": "STRING"},
        {"name": "pickupnum", "data_type": "STRING"},
        {"name": "shippingcomment", "data_type": "STRING"},
        {"name": "shipstatuscode", "data_type": "STRING"},
        {"name": "shipstatuscode_id", "data_type": "STRING"},
        {"name": "sourcesystemstatus", "data_type": "STRING"},
        {"name": "temperatureoverride", "data_type": "STRING"},
        {"name": "priority", "data_type": "STRING"},
        {"name": "priority_id", "data_type": "INTEGER"},
        {"name": "priority_ref", "data_type": "STRING"},
        {"name": "rightofplanning", "data_type": "STRING"},
        {"name": "carrier", "data_type": "STRING"},
        {"name": "carrier_id", "data_type": "STRING"},
        {"name": "altcarrierdesignation", "data_type": "STRING"},
        {"name": "incoterm", "data_type": "STRING"},
        {"name": "importtariffbook", "data_type": "STRING"},
        {"name": "importtariffbook_id", "data_type": "STRING"},
        {"name": "exporttariffbook", "data_type": "STRING"},
        {"name": "exporttariffbook_id", "data_type": "STRING"},
        {"name": "schedulesequencenum", "data_type": "INTEGER"},
        {"name": "linearspace", "data_type": "STRING"},
        {"name": "linearspace_unit", "data_type": "STRING"},
        {"name": "density", "data_type": "DOUBLE"},
        {"name": "density_unit", "data_type": "STRING"},
        {"name": "groupingid", "data_type": "STRING"}
    ],
    staging_columns = [
        "TRIM(CAST(a.shipmentid AS CHAR(30))) AS shipmentid",
        "a.integrationkey", "a.ref", "a.o_comments AS comments", "a.tmsplanningability","a.id","a.status", "a.status_id", "a.type", "a.type_id",
        "a.shipperaccountcode", "a.division", "a.division_id", "a.ordergroup", "a.ordergroup_id", "a.company", "a.company_id",
        "a.contact_id", "a.firstname", "a.lastname", "a.username", "a.ordercontact_contact_id", "a.contact_firstname",
        "a.contact_lastname", "a.contact_username", "a.createdate", "a.directioncatgid", "a.distance", "a.unit", "a.weight",
        "a.weight_unit", "a.volume", "a.volume_unit", "a.cases", "a.pallets", "a.pieces", "a.hazmat", "a.palletexchange",
        "a.billabletotal", "a.currencycode", "a.billablecalcdate", "a.freightbillableparty", "a.freightbillableparty_id",
        "a.payableallocation", "a.payableallocation_currencycode", "a.podreceived", "a.payrequirement", "a.payrequirement_id",
        "a.omsorderid", "a.omsorderlegid", "a.parentcustomer", "a.parentcustomer_id", "a.parentcustomer_ref", "a.customer",
        "a.customer_id", "a.customer_ref", "a.supplier", "a.supplier_id", "a.supplier_ref", "a.salesgroup", "a.salesgroup_id",
        "a.methodofpayment", "a.billableid", "a.trailertype", "a.nettotal", "a.nettotal_currencycode", "a.ratemthd",
        "a.billablemethod", "a.billablemethod_id", "a.valuation", "a.salesordernum", "a.shipwithref", "a.pickupnum",
        "a.shippingcomment", "a.shipstatuscode", "a.shipstatuscode_id", "a.sourcesystemstatus", "a.temperatureoverride",
        "a.priority", "a.priority_id", "a.priority_ref", "a.rightofplanning", "a.carrier", "a.carrier_id", "a.altcarrierdesignation",
        "a.incoterm", "a.importtariffbook", "a.importtariffbook_id", "a.exporttariffbook", "a.exporttariffbook_id",
        "a.schedulesequencenum", "a.linearspace", "a.linearspace_unit", "a.density", "a.density_unit", "a.groupingid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date", "a.o_SourceFileName AS SourceFileName"
    ],
    target_columns = [
        "CAST(a.shipmentid AS INT) AS shipmentid",
        "CAST(a.integrationkey AS STRING) AS integrationkey",
        "CAST(a.ref AS STRING) AS ref",
        "CAST(a.comments AS STRING) AS comments",
        "CAST(a.tmsplanningability AS STRING) AS tmsplanningability",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.status AS STRING) AS status",
        "CAST(a.status_id AS STRING) AS status_id",
        "CAST(a.type AS STRING) AS type",
        "CAST(a.type_id AS STRING) AS type_id",
        "CAST(a.shipperaccountcode AS STRING) AS shipperaccountcode",
        "CAST(a.division AS STRING) AS division",
        "CAST(a.division_id AS STRING) AS division_id",
        "CAST(a.ordergroup AS STRING) AS ordergroup",
        "CAST(a.ordergroup_id AS STRING) AS ordergroup_id",
        "CAST(a.company AS STRING) AS company",
        "CAST(a.company_id AS STRING) AS company_id",
        "CAST(a.contact_id AS STRING) AS contact_id",
        "CAST(a.firstname AS STRING) AS firstname",
        "CAST(a.lastname AS STRING) AS lastname",
        "CAST(a.username AS STRING) AS username",
        "CAST(a.ordercontact_contact_id AS STRING) AS ordercontact_contact_id",
        "CAST(a.contact_firstname AS STRING) AS contact_firstname",
        "CAST(a.contact_lastname AS STRING) AS contact_lastname",
        "CAST(a.contact_username AS STRING) AS contact_username",
        "CAST(a.createdate AS TIMESTAMP) AS createdate",
        "CAST(a.directioncatgid AS STRING) AS directioncatgid",
        "CAST(a.distance AS STRING) AS distance",
        "CAST(a.unit AS STRING) AS unit",
        "CAST(a.weight AS STRING) AS weight",
        "CAST(a.weight_unit AS STRING) AS weight_unit",
        "CAST(a.volume AS STRING) AS volume",
        "CAST(a.volume_unit AS STRING) AS volume_unit",
        "CAST(a.cases AS INT) AS cases",
        "CAST(a.pallets AS DECIMAL(14,2)) AS pallets",
        "CAST(a.pieces AS INT) AS pieces",
        "CAST(a.hazmat AS INT) AS hazmat",
        "CAST(a.palletexchange AS INT) AS palletexchange",
        "CAST(a.billabletotal AS STRING) AS billabletotal",
        "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.billablecalcdate AS STRING) AS billablecalcdate",
        "CAST(a.freightbillableparty AS STRING) AS freightbillableparty",
        "CAST(a.freightbillableparty_id AS STRING) AS freightbillableparty_id",
        "CAST(a.payableallocation AS STRING) AS payableallocation",
        "CAST(a.payableallocation_currencycode AS STRING) AS payableallocation_currencycode",
        "CAST(a.podreceived AS INT) AS podreceived",
        "CAST(a.payrequirement AS STRING) AS payrequirement",
        "CAST(a.payrequirement_id AS STRING) AS payrequirement_id",
        "CAST(a.omsorderid AS INT) AS omsorderid",
        "CAST(a.omsorderlegid AS INT) AS omsorderlegid",
        "CAST(a.parentcustomer AS STRING) AS parentcustomer",
        "CAST(a.parentcustomer_id AS STRING) AS parentcustomer_id",
        "CAST(a.parentcustomer_ref AS STRING) AS parentcustomer_ref",
        "CAST(a.customer AS STRING) AS customer",
        "CAST(a.customer_id AS STRING) AS customer_id",
        "CAST(a.customer_ref AS STRING) AS customer_ref",
        "CAST(a.supplier AS STRING) AS supplier",
        "CAST(a.supplier_id AS STRING) AS supplier_id",
        "CAST(a.supplier_ref AS STRING) AS supplier_ref",
        "CAST(a.salesgroup AS STRING) AS salesgroup",
        "CAST(a.salesgroup_id AS STRING) AS salesgroup_id",
        "CAST(a.methodofpayment AS STRING) AS methodofpayment",
        "CAST(a.billableid AS INT) AS billableid",
        "CAST(a.trailertype AS STRING) AS trailertype",
        "CAST(a.nettotal AS STRING) AS nettotal",
        "CAST(a.nettotal_currencycode AS STRING) AS nettotal_currencycode",
        "CAST(a.ratemthd AS STRING) AS ratemthd",
        "CAST(a.billablemethod AS STRING) AS billablemethod",
        "CAST(a.billablemethod_id AS STRING) AS billablemethod_id",
        "CAST(a.valuation AS DECIMAL(12,2)) AS valuation",
        "CAST(a.salesordernum AS STRING) AS salesordernum",
        "CAST(a.shipwithref AS STRING) AS shipwithref",
        "CAST(a.pickupnum AS STRING) AS pickupnum",
        "CAST(a.shippingcomment AS STRING) AS shippingcomment",
        "CAST(a.shipstatuscode AS STRING) AS shipstatuscode",
        "CAST(a.shipstatuscode_id AS STRING) AS shipstatuscode_id",
        "CAST(a.sourcesystemstatus AS STRING) AS sourcesystemstatus",
        "CAST(a.temperatureoverride AS STRING) AS temperatureoverride",
        "CAST(a.priority AS STRING) AS priority",
        "CAST(a.priority_id AS STRING) AS priority_id",
        "CAST(a.priority_ref AS STRING) AS priority_ref",
        "CAST(a.rightofplanning AS STRING) AS rightofplanning",
        "CAST(a.carrier AS STRING) AS carrier",
        "CAST(a.carrier_id AS STRING) AS carrier_id",
        "CAST(a.altcarrierdesignation AS STRING) AS altcarrierdesignation",
        "CAST(a.incoterm AS STRING) AS incoterm",
        "CAST(a.importtariffbook AS STRING) AS importtariffbook",
        "CAST(a.importtariffbook_id AS STRING) AS importtariffbook_id",
        "CAST(a.exporttariffbook AS STRING) AS exporttariffbook",
        "CAST(a.exporttariffbook_id AS STRING) AS exporttariffbook_id",
        "CAST(a.schedulesequencenum AS INT) AS schedulesequencenum",
        "CAST(a.linearspace AS STRING) AS linearspace",
        "CAST(a.linearspace_unit AS STRING) AS linearspace_unit",
        "CAST(a.density AS STRING) AS density",
        "CAST(a.density_unit AS STRING) AS density_unit",
        "CAST(a.groupingid AS STRING) AS groupingid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.createdate AS STRING) AS createdate_TimeZone",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date"
    ]
  )
}}
