{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}

{{
  load_tms_macro(
    source_path = "abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Load_RP_Routing_Step",
    merge_col = 'loadid',
	files_format = "csv",
	delimiter = '|',
    all_columns = [
        {"name": "wasrgapplied_boolean", "data_type": "INTEGER"},
        {"name": "wasrgchanged_boolean", "data_type": "INTEGER"},
        {"name": "wasrgcarrierdeleted_boolean", "data_type": "INTEGER"},
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "loadid", "data_type": "INTEGER"},
        {"name": "planid", "data_type": "INTEGER"},
        {"name": "routingguidename", "data_type": "STRING"},
        {"name": "stepid", "data_type": "INTEGER"},
        {"name": "status", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "type", "data_type": "STRING"},
        {"name": "type_id", "data_type": "INTEGER"},
        {"name": "createdbyrg", "data_type": "INTEGER"},
        {"name": "sequencenum", "data_type": "INTEGER"},
        {"name": "originalrgsequencenum", "data_type": "INTEGER"},
        {"name": "carrieravailinrg", "data_type": "INTEGER"},
        {"name": "originalratechanged", "data_type": "INTEGER"},
        {"name": "tenderid", "data_type": "INTEGER"},
        {"name": "carrier", "data_type": "STRING"},
        {"name": "carrier_id", "data_type": "INTEGER"},
        {"name": "scac", "data_type": "STRING"},
        {"name": "vendorcode", "data_type": "INTEGER"},
        {"name": "altcarrierdesignation", "data_type": "STRING"},
        {"name": "tender_status", "data_type": "STRING"},
        {"name": "status_id", "data_type": "INTEGER"},
        {"name": "tender_type", "data_type": "STRING"},
        {"name": "tender_type_id", "data_type": "INTEGER"},
        {"name": "tenderdate", "data_type": "TIMESTAMP"},
        {"name": "expiredate", "data_type": "TIMESTAMP"},
        {"name": "acceptdate", "data_type": "TIMESTAMP"},
        {"name": "tenderamt", "data_type": "DOUBLE"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "offerid", "data_type": "STRING"},
        {"name": "exchangeid", "data_type": "STRING"},
        {"name": "spotmarket", "data_type": "STRING"},
        {"name": "spotmarket_id", "data_type": "STRING"},
        {"name": "exchange_status", "data_type": "STRING"},
        {"name": "exchange_status_id", "data_type": "STRING"},
        {"name": "createdate", "data_type": "STRING"},
        {"name": "exchange_expiredate", "data_type": "STRING"},
        {"name": "voiddate", "data_type": "STRING"},
        {"name": "removedate", "data_type": "STRING"},
        {"name": "exchange_tenderdate", "data_type": "STRING"},
        {"name": "lastofferdate", "data_type": "STRING"},
        {"name": "visibility", "data_type": "STRING"},
        {"name": "visibility_id", "data_type": "STRING"},
        {"name": "reserveprice", "data_type": "STRING"},
        {"name": "reserveprice_currencycode", "data_type": "STRING"},
        {"name": "offerdecrement", "data_type": "STRING"},
        {"name": "offerdecrement_currencycode", "data_type": "STRING"},
        {"name": "autoacceptprice", "data_type": "STRING"},
        {"name": "autoacceptprice_currencycode", "data_type": "STRING"},
        {"name": "autonotifyprice", "data_type": "STRING"},
        {"name": "autonotifyprice_currencycode", "data_type": "STRING"},
        {"name": "numoffers", "data_type": "STRING"},
        {"name": "winningofferid", "data_type": "STRING"},
        {"name": "lowestofferid", "data_type": "STRING"},
        {"name": "lowestofferrate", "data_type": "STRING"},
        {"name": "lowestofferrate_currencycode", "data_type": "STRING"},
        {"name": "minservicerating", "data_type": "STRING"},
        {"name": "allowequaloffer", "data_type": "STRING"},
        {"name": "allowgreateroffer", "data_type": "STRING"},
        {"name": "allowanalysiswithdraw", "data_type": "STRING"},
        {"name": "allowcontractrate", "data_type": "STRING"},
        {"name": "contractrateonly", "data_type": "STRING"},
        {"name": "allowmultactiveoffers", "data_type": "STRING"},
        {"name": "routingguidecarriertype", "data_type": "STRING"}
    ],
    staging_columns = [
        "a.stepid", "a.status", "a.id", "a.type", "a.type_id", "a.createdbyrg",
        "a.sequencenum", "a.originalrgsequencenum", "a.carrieravailinrg",
        "a.originalratechanged", "a.tenderid", "a.carrier", "a.carrier_id",
        "a.scac", "a.vendorcode", "a.altcarrierdesignation", "a.tender_status",
        "a.status_id", "a.tender_type", "a.tender_type_id", "a.tenderdate",
        "a.expiredate", "a.acceptdate", "a.tenderamt", "a.currencycode",
        "a.offerid", "a.exchangeid", "a.spotmarket", "a.spotmarket_id",
        "a.exchange_status", "a.exchange_status_id", "a.createdate",
        "a.exchange_expiredate", "a.voiddate", "a.removedate", "a.exchange_tenderdate",
        "a.lastofferdate", "a.visibility", "a.visibility_id", "a.reserveprice",
        "a.reserveprice_currencycode", "a.offerdecrement", "a.offerdecrement_currencycode",
        "a.autoacceptprice", "a.autoacceptprice_currencycode", "a.autonotifyprice",
        "a.autonotifyprice_currencycode", "a.numoffers", "a.winningofferid",
        "a.lowestofferid", "a.lowestofferrate", "a.lowestofferrate_currencycode",
        "a.minservicerating", "a.allowequaloffer", "a.allowgreateroffer",
        "a.allowanalysiswithdraw", "a.allowcontractrate", "a.contractrateonly",
        "a.allowmultactiveoffers", "a.routingguidecarriertype", "a.planid",
        "a.wasrgapplied_boolean as wasrgapplied",
        "a.wasrgchanged_boolean as wasrgchanged",
        "a.wasrgcarrierdeleted_boolean as wasrgcarrierdeleted",
        "a.routingguidename",
        "TRIM(CAST(a.loadid AS STRING)) AS loadid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName as SourceFileName"
    ],
    target_columns = [
        "CAST(a.stepid AS INT) AS stepid",
        "CAST(a.status AS STRING) AS status",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.type AS STRING) AS type",
        "CAST(a.type_id AS STRING) AS type_id",
        "CAST(a.createdbyrg AS INT) AS createdbyrg",
        "CAST(a.sequencenum AS INT) AS sequencenum",
        "CAST(a.originalrgsequencenum AS INT) AS originalrgsequencenum",
        "CAST(a.carrieravailinrg AS INT) AS carrieravailinrg",
        "CAST(a.originalratechanged AS INT) AS originalratechanged",
        "CAST(a.tenderid AS INT) AS tenderid",
        "CAST(a.carrier AS STRING) AS carrier",
        "CAST(a.carrier_id AS STRING) AS carrier_id",
        "CAST(a.scac AS STRING) AS scac",
        "CAST(a.vendorcode AS STRING) AS vendorcode",
        "CAST(a.altcarrierdesignation AS STRING) AS altcarrierdesignation",
        "CAST(a.tender_status AS STRING) AS tender_status",
        "CAST(a.status_id AS STRING) AS status_id",
        "CAST(a.tender_type AS STRING) AS tender_type",
        "CAST(a.tender_type_id AS STRING) AS tender_type_id",
        "CAST(a.tenderdate AS STRING) AS tenderdate",
        "CAST(a.expiredate AS STRING) AS expiredate",
        "CAST(a.acceptdate AS STRING) AS acceptdate",
        "CAST(a.tenderamt AS STRING) AS tenderamt",
        "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.offerid AS INT) AS offerid",
        "CAST(a.exchangeid AS INT) AS exchangeid",
        "CAST(a.spotmarket AS STRING) AS spotmarket",
        "CAST(a.spotmarket_id AS STRING) AS spotmarket_id",
        "CAST(a.exchange_status AS STRING) AS exchange_status",
        "CAST(a.exchange_status_id AS STRING) AS exchange_status_id",
        "CAST(a.createdate AS TIMESTAMP) AS createdate",
        "CAST(a.exchange_expiredate AS STRING) AS exchange_expiredate",
        "CAST(a.voiddate AS STRING) AS voiddate",
        "CAST(a.removedate AS STRING) AS removedate",
        "CAST(a.exchange_tenderdate AS STRING) AS exchange_tenderdate",
        "CAST(a.lastofferdate AS STRING) AS lastofferdate",
        "CAST(a.visibility AS STRING) AS visibility",
        "CAST(a.visibility_id AS STRING) AS visibility_id",
        "CAST(a.reserveprice AS STRING) AS reserveprice",
        "CAST(a.reserveprice_currencycode AS STRING) AS reserveprice_currencycode",
        "CAST(a.offerdecrement AS STRING) AS offerdecrement",
        "CAST(a.offerdecrement_currencycode AS STRING) AS offerdecrement_currencycode",
        "CAST(a.autoacceptprice AS STRING) AS autoacceptprice",
        "CAST(a.autoacceptprice_currencycode AS STRING) AS autoacceptprice_currencycode",
        "CAST(a.autonotifyprice AS STRING) AS autonotifyprice",
        "CAST(a.autonotifyprice_currencycode AS STRING) AS autonotifyprice_currencycode",
        "CAST(a.numoffers AS INT) AS numoffers",
        "CAST(a.winningofferid AS INT) AS winningofferid",
        "CAST(a.lowestofferid AS INT) AS lowestofferid",
        "CAST(a.lowestofferrate AS STRING) AS lowestofferrate",
        "CAST(a.lowestofferrate_currencycode AS STRING) AS lowestofferrate_currencycode",
        "CAST(a.minservicerating AS INT) AS minservicerating",
        "CAST(a.allowequaloffer AS INT) AS allowequaloffer",
        "CAST(a.allowgreateroffer AS INT) AS allowgreateroffer",
        "CAST(a.allowanalysiswithdraw AS INT) AS allowanalysiswithdraw",
        "CAST(a.allowcontractrate AS INT) AS allowcontractrate",
        "CAST(a.contractrateonly AS INT) AS contractrateonly",
        "CAST(a.allowmultactiveoffers AS INT) AS allowmultactiveoffers",
        "CAST(a.routingguidecarriertype AS STRING) AS routingguidecarriertype",
        "CAST(a.planid AS INT) AS planid",
        "CAST(a.wasrgapplied AS INT) AS wasrgapplied",
        "CAST(a.wasrgchanged AS INT) AS wasrgchanged",
        "CAST(a.wasrgcarrierdeleted AS INT) AS wasrgcarrierdeleted",
        "CAST(a.routingguidename AS STRING) AS routingguidename",
        "CAST(a.loadid AS INT) AS loadid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.createdate AS STRING) AS createdate_TimeZone",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date"
    ]
  )
}}
