{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}

{{
  load_tms_macro(
    source_path = "abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Load",
    merge_col = 'loadid',
	  files_format = "csv",
	  delimiter = '|',
    all_columns = [
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "o_comments", "data_type": "STRING"},
        {"name": "loadid", "data_type": "INTEGER"},
        {"name": "company", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "shipperloadref", "data_type": "INTEGER"},
        {"name": "shipperintgkey", "data_type": "INTEGER"},
        {"name": "status", "data_type": "STRING"},
        {"name": "status_id", "data_type": "INTEGER"},
        {"name": "type", "data_type": "STRING"},
        {"name": "type_id", "data_type": "INTEGER"},
        {"name": "loadgroup", "data_type": "STRING"},
        {"name": "loadgroup_id", "data_type": "INTEGER"},
        {"name": "contact_id", "data_type": "INTEGER"},
        {"name": "firstname", "data_type": "STRING"},
        {"name": "lastname", "data_type": "STRING"},
        {"name": "username", "data_type": "STRING"},
        {"name": "createdate", "data_type": "TIMESTAMP"},
        {"name": "closedate", "data_type": "TIMESTAMP"},
        {"name": "voiddate", "data_type": "STRING"},
        {"name": "trailer", "data_type": "STRING"},
        {"name": "trailer_id", "data_type": "INTEGER"},
        {"name": "trailerref", "data_type": "STRING"},
        {"name": "transmode", "data_type": "STRING"},
        {"name": "servicelevel", "data_type": "STRING"},
        {"name": "servicelevel_id", "data_type": "INTEGER"},
        {"name": "servicelevelext", "data_type": "STRING"},
        {"name": "servicelevelext_id", "data_type": "STRING"},
        {"name": "numstops", "data_type": "INTEGER"},
        {"name": "distance", "data_type": "INTEGER"},
        {"name": "unit", "data_type": "STRING"},
        {"name": "backhauldistance", "data_type": "INTEGER"},
        {"name": "backhauldistance_unit", "data_type": "STRING"},
        {"name": "weight", "data_type": "INTEGER"},
        {"name": "weight_unit", "data_type": "STRING"},
        {"name": "volume", "data_type": "INTEGER"},
        {"name": "volume_unit", "data_type": "STRING"},
        {"name": "pallets", "data_type": "DOUBLE"},
        {"name": "pieces", "data_type": "INTEGER"},
        {"name": "hazmat", "data_type": "INTEGER"},
        {"name": "palletexchange", "data_type": "INTEGER"},
        {"name": "temperature", "data_type": "STRING"},
        {"name": "temperature_id", "data_type": "STRING"},
        {"name": "edicode", "data_type": "STRING"},
        {"name": "shipperaccountcode", "data_type": "STRING"},
        {"name": "billabletotal", "data_type": "STRING"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "exchangeid", "data_type": "INTEGER"},
        {"name": "tourid", "data_type": "STRING"},
        {"name": "previousdroplotloadid", "data_type": "STRING"},
        {"name": "nextdroplotloadid", "data_type": "STRING"},
        {"name": "tenderid", "data_type": "INTEGER"},
        {"name": "carrier", "data_type": "STRING"},
        {"name": "carrier_id", "data_type": "INTEGER"},
        {"name": "scac", "data_type": "STRING"},
        {"name": "vendorcode", "data_type": "STRING"},
        {"name": "altcarrierdesignation", "data_type": "STRING"},
        {"name": "tender_status", "data_type": "STRING"},
        {"name": "tender_status_id", "data_type": "INTEGER"},
        {"name": "tender_type", "data_type": "STRING"},
        {"name": "tender_type_id", "data_type": "INTEGER"},
        {"name": "tenderdate", "data_type": "TIMESTAMP"},
        {"name": "expiredate", "data_type": "TIMESTAMP"},
        {"name": "acceptdate", "data_type": "TIMESTAMP"},
        {"name": "tenderamt", "data_type": "DOUBLE"},
        {"name": "tenderamt_currencycode", "data_type": "STRING"},
        {"name": "offerid", "data_type": "INTEGER"},
        {"name": "priority", "data_type": "STRING"},
        {"name": "priority_id", "data_type": "INTEGER"},
        {"name": "ref", "data_type": "STRING"},
        {"name": "drivername", "data_type": "STRING"},
        {"name": "vehiclenum", "data_type": "STRING"},
        {"name": "vesselbookingid", "data_type": "STRING"},
        {"name": "linearspace", "data_type": "STRING"},
        {"name": "linearspace_unit", "data_type": "STRING"},
        {"name": "density", "data_type": "DOUBLE"},
        {"name": "density_unit", "data_type": "STRING"},
        {"name": "creationprocess", "data_type": "STRING"},
        {"name": "creationprocess_id", "data_type": "INTEGER"},
        {"name": "roundtrip", "data_type": "INTEGER"},
        {"name": "directioncategory", "data_type": "STRING"},
        {"name": "directioncategory_id", "data_type": "STRING"},
        {"name": "assettype", "data_type": "STRING"},
        {"name": "assettype_id", "data_type": "STRING"}
    ],
    staging_columns = [
        "TRIM(CAST(a.loadid AS CHAR(30))) AS loadid", "a.company", "a.id",
        "a.shipperloadref", "a.shipperintgkey", "a.status", "a.status_id", "a.type",
        "a.type_id", "a.loadgroup", "a.loadgroup_id", "a.contact_id", "a.firstname",
        "a.lastname", "a.username", "a.createdate", "a.closedate", "a.voiddate",
        "a.trailer", "a.trailer_id", "a.trailerref", "a.transmode", "a.servicelevel",
        "a.servicelevel_id", "a.servicelevelext", "a.servicelevelext_id", "a.numstops",
        "a.distance", "a.unit", "a.backhauldistance", "a.backhauldistance_unit",
        "a.weight", "a.weight_unit", "a.volume", "a.volume_unit", "a.pallets", "a.pieces",
        "a.hazmat", "a.palletexchange", "a.temperature", "a.temperature_id", "a.edicode",
        "a.shipperaccountcode", "a.billabletotal", "a.currencycode", "a.exchangeid",
        "a.tourid", "a.previousdroplotloadid", "a.nextdroplotloadid", "a.tenderid",
        "a.carrier", "a.carrier_id", "a.scac", "a.vendorcode", "a.altcarrierdesignation",
        "a.tender_status", "a.tender_status_id", "a.tender_type", "a.tender_type_id",
        "a.tenderdate", "a.expiredate", "a.acceptdate", "a.tenderamt",
        "a.tenderamt_currencycode", "a.offerid", "a.o_comments AS comments", "a.priority",
        "a.priority_id", "a.ref", "a.drivername", "a.vehiclenum", "a.vesselbookingid",
        "a.linearspace", "a.linearspace_unit", "a.density", "a.density_unit",
        "a.creationprocess", "a.creationprocess_id", "a.roundtrip", "a.directioncategory",
        "a.directioncategory_id",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName AS SourceFileName", "a.AssetType", "a.Assettype_id"
    ],
    target_columns = [
        "CAST(a.loadid AS INT) AS loadid",
        "CAST(a.company AS STRING) AS company",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.shipperloadref AS STRING) AS shipperloadref",
        "CAST(a.shipperintgkey AS STRING) AS shipperintgkey",
        "CAST(a.status AS STRING) AS status",
        "CAST(a.status_id AS STRING) AS status_id",
        "CAST(a.type AS STRING) AS type",
        "CAST(a.type_id AS STRING) AS type_id",
        "CAST(a.loadgroup AS STRING) AS loadgroup",
        "CAST(a.loadgroup_id AS STRING) AS loadgroup_id",
        "CAST(a.contact_id AS STRING) AS contact_id",
        "CAST(a.firstname AS STRING) AS firstname",
        "CAST(a.lastname AS STRING) AS lastname",
        "CAST(a.username AS STRING) AS username",
        "CAST(a.createdate AS TIMESTAMP) AS createdate",
        "CAST(a.closedate AS STRING) AS closedate",
        "CAST(a.voiddate AS STRING) AS voiddate",
        "CAST(a.trailer AS STRING) AS trailer",
        "CAST(a.trailer_id AS STRING) AS trailer_id",
        "CAST(a.trailerref AS STRING) AS trailerref",
        "CAST(a.transmode AS STRING) AS transmode",
        "CAST(a.servicelevel AS STRING) AS servicelevel",
        "CAST(a.servicelevel_id AS STRING) AS servicelevel_id",
        "CAST(a.servicelevelext AS STRING) AS servicelevelext",
        "CAST(a.servicelevelext_id AS STRING) AS servicelevelext_id",
        "CAST(a.numstops AS INT) AS numstops",
        "CAST(a.distance AS STRING) AS distance",
        "CAST(a.unit AS STRING) AS unit",
        "CAST(a.backhauldistance AS STRING) AS backhauldistance",
        "CAST(a.backhauldistance_unit AS STRING) AS backhauldistance_unit",
        "CAST(a.weight AS STRING) AS weight",
        "CAST(a.weight_unit AS STRING) AS weight_unit",
        "CAST(a.volume AS STRING) AS volume",
        "CAST(a.volume_unit AS STRING) AS volume_unit",
        "CAST(a.pallets AS DECIMAL(14,2)) AS pallets",
        "CAST(a.pieces AS INT) AS pieces",
        "CAST(a.hazmat AS INT) AS hazmat",
        "CAST(a.palletexchange AS INT) AS palletexchange",
        "CAST(a.temperature AS STRING) AS temperature",
        "CAST(a.temperature_id AS STRING) AS temperature_id",
        "CAST(a.edicode AS STRING) AS edicode",
        "CAST(a.shipperaccountcode AS STRING) AS shipperaccountcode",
        "CAST(a.billabletotal AS DOUBLE) AS billabletotal",
        "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.exchangeid AS INT) AS exchangeid",
        "CAST(a.tourid AS INT) AS tourid",
        "CAST(a.previousdroplotloadid AS INT) AS previousdroplotloadid",
        "CAST(a.nextdroplotloadid AS INT) AS nextdroplotloadid",
        "CAST(a.tenderid AS INT) AS tenderid",
        "CAST(a.carrier AS STRING) AS carrier",
        "CAST(a.carrier_id AS STRING) AS carrier_id",
        "CAST(a.scac AS STRING) AS scac",
        "CAST(a.vendorcode AS STRING) AS vendorcode",
        "CAST(a.altcarrierdesignation AS STRING) AS altcarrierdesignation",
        "CAST(a.tender_status AS STRING) AS tender_status",
        "CAST(a.tender_status_id AS STRING) AS tender_status_id",
        "CAST(a.tender_type AS STRING) AS tender_type",
        "CAST(a.tender_type_id AS STRING) AS tender_type_id",
        "CAST(a.tenderdate AS STRING) AS tenderdate",
        "CAST(a.expiredate AS STRING) AS expiredate",
        "CAST(a.acceptdate AS STRING) AS acceptdate",
        "CAST(a.tenderamt AS STRING) AS tenderamt",
        "CAST(a.tenderamt_currencycode AS STRING) AS tenderamt_currencycode",
        "CAST(a.offerid AS INT) AS offerid",
        "CAST(a.comments AS STRING) AS comments",
        "CAST(a.priority AS STRING) AS priority",
        "CAST(a.priority_id AS STRING) AS priority_id",
        "CAST(a.ref AS STRING) AS ref",
        "CAST(a.drivername AS STRING) AS drivername",
        "CAST(a.vehiclenum AS STRING) AS vehiclenum",
        "CAST(a.vesselbookingid AS INT) AS vesselbookingid",
        "CAST(a.linearspace AS STRING) AS linearspace",
        "CAST(a.linearspace_unit AS STRING) AS linearspace_unit",
        "CAST(a.density AS STRING) AS density",
        "CAST(a.density_unit AS STRING) AS density_unit",
        "CAST(a.creationprocess AS STRING) AS creationprocess",
        "CAST(a.creationprocess_id AS STRING) AS creationprocess_id",
        "CAST(a.roundtrip AS INT) AS roundtrip",
        "CAST(a.directioncategory AS STRING) AS directioncategory",
        "CAST(a.directioncategory_id AS STRING) AS directioncategory_id",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.createdate AS STRING) AS createdate_TimeZone",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "CAST(a.AssetType AS STRING) AS AssetType",
        "CAST(a.Assettype_id AS STRING) AS Assettype_id"
    ]
  )
}}
