{% set container_value1 = var('container_1') %}
{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}


{{ load_tms_macro(
    source_path="abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Load_Stop_Shipment_Leg_Id",
	merge_col = 'loadid',
    files_format = "csv",
    delimiter = '|',
    all_columns = [
        {"name": "enddate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "etadate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "actualarrivaldate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "actualdeparturedate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "calculatedduedate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "startdate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "appointment_enddate_ignoretime_boolean", "data_type": "INTEGER"},
        {"name": "name", "data_type": "STRING"},
        {"name": "appointment_ref", "data_type": "STRING"},
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "loadid", "data_type": "INTEGER"},
        {"name": "stopid", "data_type": "INTEGER"},
        {"name": "type", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "ref", "data_type": "STRING"},
        {"name": "address1", "data_type": "STRING"},
        {"name": "address2", "data_type": "STRING"},
        {"name": "address3", "data_type": "STRING"},
        {"name": "city", "data_type": "STRING"},
        {"name": "state", "data_type": "STRING"},
        {"name": "zip", "data_type": "STRING"},
        {"name": "country", "data_type": "STRING"},
        {"name": "timezone", "data_type": "STRING"},
        {"name": "dst", "data_type": "INTEGER"},
        {"name": "timezoneid", "data_type": "STRING"},
        {"name": "contactname", "data_type": "STRING"},
        {"name": "contactphonenum", "data_type": "STRING"},
        {"name": "contactphoneext", "data_type": "INTEGER"},
        {"name": "apptcontactname", "data_type": "STRING"},
        {"name": "apptcontactphonenum", "data_type": "STRING"},
        {"name": "apptcontactphoneext", "data_type": "STRING"},
        {"name": "sequencenum", "data_type": "INTEGER"},
        {"name": "startdate", "data_type": "TIMESTAMP"},
        {"name": "ignoretime", "data_type": "BOOLEAN"},
        {"name": "enddate", "data_type": "TIMESTAMP"},
        {"name": "etadate", "data_type": "TIMESTAMP"},
        {"name": "actualarrivaldate", "data_type": "TIMESTAMP"},
        {"name": "actualdeparturedate", "data_type": "TIMESTAMP"},
        {"name": "calculatedduedate", "data_type": "TIMESTAMP"},
        {"name": "appointment_startdate", "data_type": "TIMESTAMP"},
        {"name": "appointment_enddate", "data_type": "TIMESTAMP"},
        {"name": "fcfs", "data_type": "INTEGER"},
        {"name": "status", "data_type": "STRING"},
        {"name": "status_id", "data_type": "INTEGER"},
        {"name": "entityid", "data_type": "INTEGER"},
        {"name": "username", "data_type": "STRING"},
        {"name": "createdate", "data_type": "TIMESTAMP"},
        {"name": "scheduledondate", "data_type": "TIMESTAMP"},
        {"name": "priority", "data_type": "STRING"},
        {"name": "priority_id", "data_type": "INTEGER"},
        {"name": "priority_ref", "data_type": "STRING"},
        {"name": "distance", "data_type": "INTEGER"},
        {"name": "unit", "data_type": "STRING"},
        {"name": "weight", "data_type": "DOUBLE"},
        {"name": "weight_unit", "data_type": "STRING"},
        {"name": "volume", "data_type": "DOUBLE"},
        {"name": "volume_unit", "data_type": "STRING"},
        {"name": "pallets", "data_type": "DOUBLE"},
        {"name": "pieces", "data_type": "INTEGER"},
        {"name": "combined", "data_type": "INTEGER"},
        {"name": "trailerloadingtype", "data_type": "STRING"},
        {"name": "trailerloadingtype_id", "data_type": "INTEGER"},
        {"name": "shipmentlegid", "data_type": "INTEGER"}
    ],
    staging_columns = [
        "a.shipmentlegid","a.stopid","a.type",
        "a.id",
        "a.ref",
        "a.name",
        "a.address1",
        "a.address2",
        "a.address3",
        "a.city",
        "a.state",
        "a.zip",
        "a.country",
        "a.timezone",
        "a.dst",
        "a.timezoneid",
        "a.contactname",
        "a.contactphonenum",
        "a.contactphoneext",
        "a.apptcontactname",
        "a.apptcontactphonenum",
        "a.apptcontactphoneext",
        "a.sequencenum",
        "a.startdate",
        "CASE WHEN a.ignoretime='false' THEN 0 ELSE 1 END as ignoretime",
        "a.enddate",
        "a.enddate_ignoretime_boolean as enddate_ignoretime",
        "a.etadate",
        "a.etadate_ignoretime_boolean as etadate_ignoretime",
        "a.actualarrivaldate",
        "a.actualarrivaldate_ignoretime_boolean as actualarrivaldate_ignoretime",
        "a.actualdeparturedate",
        "a.actualdeparturedate_ignoretime_boolean as actualdeparturedate_ignoretime",
        "a.calculatedduedate",
        "a.calculatedduedate_ignoretime_boolean as calculatedduedate_ignoretime",
        "a.appointment_ref",
        "a.appointment_startdate",
        "a.startdate_ignoretime_boolean as startdate_ignoretime",
        "a.appointment_enddate",
        "a.appointment_enddate_ignoretime_boolean AS appointment_enddate_ignoretime",
        "a.fcfs",
        "a.status",
        "a.status_id",
        "a.entityid",
        "a.username",
        "a.createdate",
        "a.scheduledondate",
        "a.priority",
        "a.priority_id",
        "a.priority_ref",
        "a.distance",
        "a.unit",
        "a.weight",
        "a.weight_unit",
        "a.volume",
        "a.volume_unit",
        "a.pallets",
        "a.pieces",
        "a.combined",
        "a.trailerloadingtype",
        "a.trailerloadingtype_id",
        "TRIM(CAST(a.loadid AS CHAR(30))) AS loadid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName AS SourceFileName"
    ],
    target_columns = [
        "CAST(a.shipmentlegid AS STRING) AS shipmentlegid",
        "CAST(a.stopid AS INT) AS stopid",
        "CAST(a.type AS STRING) AS type",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.ref AS STRING) AS ref",
        "CAST(a.name AS STRING) AS name",
        "CAST(a.address1 AS STRING) AS address1",
        "CAST(a.address2 AS STRING) AS address2",
        "CAST(a.address3 AS STRING) AS address3",
        "CAST(a.city AS STRING) AS city",
        "CAST(a.state AS STRING) AS state",
        "CAST(a.zip AS STRING) AS zip",
        "CAST(a.country AS STRING) AS country",
        "CAST(a.timezone AS STRING) AS timezone",
        "CAST(a.dst AS INT) AS dst",
        "CAST(a.timezoneid AS STRING) AS timezoneid",
        "CAST(a.contactname AS STRING) AS contactname",
        "CAST(a.contactphonenum AS STRING) AS contactphonenum",
        "CAST(a.contactphoneext AS STRING) AS contactphoneext",
        "CAST(a.apptcontactname AS STRING) AS apptcontactname",
        "CAST(a.apptcontactphonenum AS STRING) AS apptcontactphonenum",
        "CAST(a.apptcontactphoneext AS STRING) AS apptcontactphoneext",
        "CAST(a.sequencenum AS INT) AS sequencenum",
        "CAST(a.startdate AS STRING) AS startdate",
        "CAST(a.ignoretime AS INT) AS ignoretime",
        "CAST(a.enddate AS STRING) AS enddate",
        "CAST(a.enddate_ignoretime AS INT) AS enddate_ignoretime",
        "CAST(a.etadate AS STRING) AS etadate",
        "CAST(a.etadate_ignoretime AS INT) AS etadate_ignoretime",
        "CAST(a.actualarrivaldate AS STRING) AS actualarrivaldate",
        "CAST(a.actualarrivaldate_ignoretime AS INT) AS actualarrivaldate_ignoretime",
        "CAST(a.actualdeparturedate AS STRING) AS actualdeparturedate",
        "CAST(a.actualdeparturedate_ignoretime AS INT) AS actualdeparturedate_ignoretime",
        "CAST(a.calculatedduedate AS STRING) AS calculatedduedate",
        "CAST(a.calculatedduedate_ignoretime AS INT) AS calculatedduedate_ignoretime",
        "CAST(a.appointment_ref AS STRING) AS appointment_ref",
        "CAST(a.appointment_startdate AS STRING) AS appointment_startdate",
        "CAST(a.startdate_ignoretime AS INT) AS startdate_ignoretime",
        "CAST(a.appointment_enddate AS STRING) AS appointment_enddate",
        "CAST(a.appointment_enddate_ignoretime AS INT) AS appointment_enddate_ignoretime",
        "CAST(a.fcfs AS INT) AS fcfs",
        "CAST(a.status AS STRING) AS status",
        "CAST(a.status_id AS STRING) AS status_id",
        "CAST(a.entityid AS INT) AS entityid",
        "CAST(a.username AS STRING) AS username",
        "CAST(a.createdate AS TIMESTAMP) AS createdate",
        "CAST(a.scheduledondate AS STRING) AS scheduledondate",
        "CAST(a.priority AS STRING) AS priority",
        "CAST(a.priority_id AS STRING) AS priority_id",
        "CAST(a.priority_ref AS STRING) AS priority_ref",
        "CAST(a.distance AS STRING) AS distance",
        "CAST(a.unit AS STRING) AS unit",
        "CAST(a.weight AS STRING) AS weight",
        "CAST(a.weight_unit AS STRING) AS weight_unit",
        "CAST(a.volume AS STRING) AS volume",
        "CAST(a.volume_unit AS STRING) AS volume_unit",
        "CAST(a.pallets AS DECIMAL(14,2)) AS pallets",
        "CAST(a.pieces AS INT) AS pieces",
        "CAST(a.combined AS INT) AS combined",
        "CAST(a.trailerloadingtype AS STRING) AS trailerloadingtype",
        "CAST(a.trailerloadingtype_id AS STRING) AS trailerloadingtype_id",
        "CAST(a.loadid AS INT) AS loadid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date",
        "CAST(a.createdate AS STRING) AS createdate_TimeZone"
    ]

) }}