{% set container_value1 = var('container_1') %}
{% set container_value2 = var('container_2') %}
{% set storage_account_value = var('storage_account') %}


{{ load_tms_macro(
    source_path="abfss://" ~ container_value2 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/TMS/Temp_TMS_Shipment_Order_Schedule_Item",
	merge_col = 'shipmentid',
    files_format = "csv",
    delimiter = '|',
    all_columns = [
        {"name": "description", "data_type": "STRING"},
        {"name": "processing_date", "data_type": "STRING"},
        {"name": "o_SourceFileName", "data_type": "STRING"},
        {"name": "shipmentid", "data_type": "INTEGER"},
        {"name": "omsorderid", "data_type": "INTEGER"},
        {"name": "omsorderlegid", "data_type": "INTEGER"},
        {"name": "sequencenum", "data_type": "INTEGER"},
        {"name": "integrationkey", "data_type": "STRING"},
        {"name": "commodity", "data_type": "STRING"},
        {"name": "id", "data_type": "INTEGER"},
        {"name": "orderlinenumber", "data_type": "INTEGER"},
        {"name": "productid", "data_type": "STRING"},
        {"name": "packagequantity", "data_type": "INTEGER"},
        {"name": "packagetype", "data_type": "STRING"},
        {"name": "packagetype_id", "data_type": "INTEGER"},
        {"name": "ladingquantity", "data_type": "DOUBLE"},
        {"name": "ladingtype", "data_type": "STRING"},
        {"name": "ladingtype_id", "data_type": "STRING"},
        {"name": "weight", "data_type": "DOUBLE"},
        {"name": "unit", "data_type": "STRING"},
        {"name": "volume", "data_type": "DOUBLE"},
        {"name": "volume_unit", "data_type": "STRING"},
        {"name": "payableallocation", "data_type": "DOUBLE"},
        {"name": "currencycode", "data_type": "STRING"},
        {"name": "freightclass", "data_type": "STRING"},
        {"name": "importtariffcode", "data_type": "STRING"},
        {"name": "importtariffcodesrc", "data_type": "STRING"},
        {"name": "importtariffcodesrc_id", "data_type": "STRING"},
        {"name": "exporttariffcode", "data_type": "STRING"},
        {"name": "exporttariffcodesrc", "data_type": "STRING"},
        {"name": "exporttariffcodesrc_id", "data_type": "STRING"},
        {"name": "exportcontrolnum", "data_type": "STRING"}
    ],
    staging_columns = [
        "a.omsorderid", "a.omsorderlegid", "a.sequencenum", "a.integrationkey",
        "a.commodity", "a.id", "a.orderlinenumber", "a.productid",
        "a.description", "a.packagequantity", "a.packagetype", "a.packagetype_id",
        "a.ladingquantity", "a.ladingtype", "a.ladingtype_id", "a.weight",
        "a.unit", "a.volume", "a.volume_unit", "a.payableallocation",
        "a.currencycode", "a.freightclass", "a.importtariffcode", "a.importtariffcodesrc",
        "a.importtariffcodesrc_id", "a.exporttariffcode", "a.exporttariffcodesrc", "a.exporttariffcodesrc_id",
        "a.exportcontrolnum",
        "TRIM(CAST(a.shipmentid AS CHAR(30))) AS shipmentid",
        "TO_TIMESTAMP(a.processing_date, 'MM/dd/yyyy HH:mm:ss.SSSSSS') AS processing_date",
        "a.o_SourceFileName AS SourceFileName"
    ],
    target_columns = [
        "CAST(a.omsorderid AS INT) AS omsorderid",
        "CAST(a.omsorderlegid AS INT) AS omsorderlegid",
        "CAST(a.sequencenum AS INT) AS sequencenum",
        "CAST(a.integrationkey AS STRING) AS integrationkey",
        "CAST(a.commodity AS STRING) AS commodity",
        "CAST(a.id AS STRING) AS id",
        "CAST(a.orderlinenumber AS INT) AS orderlinenumber",
        "CAST(a.productid AS STRING) AS productid",
        "CAST(a.description AS STRING) AS description",
        "CAST(a.packagequantity AS INT) AS packagequantity",
        "CAST(a.packagetype AS STRING) AS packagetype",
        "CAST(a.packagetype_id AS STRING) AS packagetype_id",
        "CAST(a.ladingquantity AS DECIMAL(14,2)) AS ladingquantity",
        "CAST(a.ladingtype AS STRING) AS ladingtype",
        "CAST(a.ladingtype_id AS STRING) AS ladingtype_id",
        "CAST(a.weight AS STRING) AS weight",
        "CAST(a.unit AS STRING) AS unit",
        "CAST(a.volume AS STRING) AS volume",
        "CAST(a.volume_unit AS STRING) AS volume_unit",
        "CAST(a.payableallocation AS STRING) AS payableallocation",
        "CAST(a.currencycode AS STRING) AS currencycode",
        "CAST(a.freightclass AS STRING) AS freightclass",
        "CAST(a.importtariffcode AS STRING) AS importtariffcode",
        "CAST(a.importtariffcodesrc AS STRING) AS importtariffcodesrc",
        "CAST(a.importtariffcodesrc_id AS STRING) AS importtariffcodesrc_id",
        "CAST(a.exporttariffcode AS STRING) AS exporttariffcode",
        "CAST(a.exporttariffcodesrc AS STRING) AS exporttariffcodesrc",
        "CAST(a.exporttariffcodesrc_id AS STRING) AS exporttariffcodesrc_id",
        "CAST(a.exportcontrolnum AS STRING) AS exportcontrolnum",
        "CAST(a.shipmentid AS INT) AS shipmentid",
        "CAST(a.processing_date AS TIMESTAMP) AS processing_date",
        "CAST(a.SourceFileName AS STRING) AS SourceFileName",
        "DATEADD(SECOND, CAST(SUBSTRING(a.SourceFileName, CHARINDEX('-', a.SourceFileName, CHARINDEX('-', a.SourceFileName, 11)+1)+1, 10) AS INT), CAST('1970-01-01' AS TIMESTAMP)) AS SourceFile_date"
    ]
) }}