{% set container_value1 = var('container_1') %}
{% set storage_account_value = var('storage_account') %}
{% set incremental_location_value = var('incremental_location') %}

{{ load_wms_incremental(
    source_path="abfss://" ~ container_value1 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_location_value ~ "/COL/WMS_TFOOD_COL_500_parquet",
    all_columns = [
        {"name": "ODORG", "data_type": "STRING"},
        {"name": "ODPL#", "data_type": "DECIMAL(9,0)"},
        {"name": "ODSWHS", "data_type": "STRING"},
        {"name": "ODORTP", "data_type": "STRING"},
        {"name": "ODPOOR", "data_type": "STRING"},
        {"name": "ODTOLN", "data_type": "DECIMAL(7,0)"},
        {"name": "ODTOOR", "data_type": "DECIMAL(9,0)"},
        {"name": "ODSHOR", "data_type": "DECIMAL(9,0)"},
        {"name": "ODPKOR", "data_type": "DECIMAL(9,0)"},
        {"name": "ODPKLN", "data_type": "DECIMAL(7,0)"},
        {"name": "ODPKAC", "data_type": "STRING"},
        {"name": "ODITM", "data_type": "STRING"},
        {"name": "ODVRSN", "data_type": "STRING"},
        {"name": "ODITMX", "data_type": "STRING"},
        {"name": "ODCITM", "data_type": "STRING"},
        {"name": "ODISTS", "data_type": "STRING"},
        {"name": "ODIDSC", "data_type": "STRING"},
        {"name": "ODICTP", "data_type": "STRING"},
        {"name": "ODIVND", "data_type": "STRING"},
        {"name": "ODLOT", "data_type": "STRING"},
        {"name": "ODLFT", "data_type": "STRING"},
        {"name": "ODLED", "data_type": "DECIMAL(3,0)"},
        {"name": "ODCSID", "data_type": "STRING"},
        {"name": "ODC#OR", "data_type": "DECIMAL(13,0)"},
        {"name": "ODCUOM", "data_type": "STRING"},
        {"name": "OD#ORD", "data_type": "DECIMAL(13,0)"},
        {"name": "OD#ALC", "data_type": "DECIMAL(13,0)"},
        {"name": "OD#RJ", "data_type": "DECIMAL(13,0)"},
        {"name": "OD#SH", "data_type": "DECIMAL(13,0)"},
        {"name": "ODPCVL", "data_type": "DECIMAL(13,2)"},
        {"name": "ODPCWT", "data_type": "DECIMAL(13,5)"},
        {"name": "ODPCLN", "data_type": "DECIMAL(13,5)"},
        {"name": "ODPCWD", "data_type": "DECIMAL(13,5)"},
        {"name": "ODPCHT", "data_type": "DECIMAL(13,5)"},
        {"name": "ODCAWT", "data_type": "DECIMAL(13,5)"},
        {"name": "ODCALN", "data_type": "DECIMAL(13,5)"},
        {"name": "ODCAWD", "data_type": "DECIMAL(13,5)"},
        {"name": "ODCAHT", "data_type": "DECIMAL(13,5)"},
        {"name": "ODPCCA", "data_type": "DECIMAL(5,0)"},
        {"name": "ODCARQ", "data_type": "DECIMAL(5,0)"},
        {"name": "ODLTPC", "data_type": "DECIMAL(13,2)"},
        {"name": "ODNTPC", "data_type": "DECIMAL(13,2)"},
        {"name": "ODDCT", "data_type": "DECIMAL(5,2)"},
        {"name": "ODNMFC", "data_type": "STRING"},
        {"name": "ODLCN", "data_type": "STRING"},
        {"name": "ODDEPT", "data_type": "STRING"},
        {"name": "ODCLS", "data_type": "DECIMAL(5,1)"},
        {"name": "ODPLBS", "data_type": "DECIMAL(3,0)"},
        {"name": "ODSHPC", "data_type": "STRING"},
        {"name": "ODINDT", "data_type": "DECIMAL(7,0)"},
        {"name": "ODSCOM", "data_type": "STRING"},
        {"name": "ODABO", "data_type": "STRING"},
        {"name": "ODKIT", "data_type": "STRING"},
        {"name": "ODKTLN", "data_type": "DECIMAL(7,0)"},
        {"name": "ODXPLQ", "data_type": "DECIMAL(13,0)"},
        {"name": "ODXCDE", "data_type": "STRING"},
        {"name": "ODXDTE", "data_type": "DECIMAL(7,0)"},
        {"name": "ODXDSC", "data_type": "STRING"},
        {"name": "ODRJCD", "data_type": "DECIMAL(5,0)"},
        {"name": "ODPCDE", "data_type": "STRING"},
        {"name": "ODDDTE", "data_type": "DECIMAL(7,0)"},
        {"name": "ODDTME", "data_type": "DECIMAL(7,0)"},
        {"name": "ODDUSR", "data_type": "STRING"},
        {"name": "ODSDTE", "data_type": "DECIMAL(7,0)"},
        {"name": "ODSTME", "data_type": "DECIMAL(7,0)"},
        {"name": "ODSUSR", "data_type": "STRING"},
        {"name": "ODSTS", "data_type": "STRING"},
        {"name": "ODUD20", "data_type": "STRING"},
        {"name": "ODUD30", "data_type": "STRING"},
        {"name": "ODUD40", "data_type": "STRING"}
    ]
) }}