{% set container_value1 = var('container_1') %}
{% set storage_account_value = var('storage_account') %}
{% set incremental_location_value = var('incremental_location') %}

{{ load_wms_incremental(
    source_path="abfss://" ~ container_value1 ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_location_value ~ "/USA/WMS_WFTRH_USA_77_parquet",
    all_columns = [
        {"name": "THHSEQ", "data_type": "DECIMAL(9,0)"},
        {"name": "THWHS", "data_type": "STRING"},
        {"name": "THASLE", "data_type": "STRING"},
        {"name": "THBAY", "data_type": "STRING"},
        {"name": "THLVL", "data_type": "STRING"},
        {"name": "THITEM", "data_type": "STRING"},
        {"name": "THVRSN", "data_type": "STRING"},
        {"name": "THLCPL", "data_type": "DECIMAL(20,0)"},
        {"name": "THOLCP", "data_type": "DECIMAL(20,0)"},
        {"name": "THWLLP", "data_type": "DECIMAL(20,0)"},
        {"name": "THLOT", "data_type": "STRING"},
        {"name": "THISTS", "data_type": "STRING"},
        {"name": "THSRCM", "data_type": "STRING"},
        {"name": "THTXN", "data_type": "STRING"},
        {"name": "THTTYP", "data_type": "STRING"},
        {"name": "THUD15", "data_type": "STRING"},
        {"name": "THRSRT", "data_type": "STRING"},
        {"name": "THRLSQ", "data_type": "STRING"},
        {"name": "THADAT", "data_type": "DECIMAL(7,0)"},
        {"name": "THCSPK", "data_type": "DECIMAL(5,0)"},
        {"name": "THCSPL", "data_type": "DECIMAL(5,0)"},
        {"name": "THPOHQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THPITQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THPALQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THOHQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THITQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THALQ", "data_type": "DECIMAL(13,0)"},
        {"name": "THTUSR", "data_type": "STRING"},
        {"name": "THTEAM", "data_type": "STRING"},
        {"name": "THTWRK", "data_type": "STRING"},
        {"name": "THTMBR", "data_type": "DECIMAL(5,0)"},
        {"name": "THTQTY", "data_type": "DECIMAL(13,0)"},
        {"name": "THINTF", "data_type": "STRING"},
        {"name": "THIDAT", "data_type": "DECIMAL(7,0)"},
        {"name": "THITIM", "data_type": "DECIMAL(7,0)"},
        {"name": "THIUSR", "data_type": "STRING"},
        {"name": "THDATS", "data_type": "DECIMAL(7,0)"},
        {"name": "THTIMS", "data_type": "DECIMAL(7,0)"},
        {"name": "THUSRS", "data_type": "STRING"},
        {"name": "THGLAC", "data_type": "DECIMAL(25,0)"},
        {"name": "THGLCP", "data_type": "DECIMAL(4,0)"},
        {"name": "THNRCV", "data_type": "STRING"},
        {"name": "THLIN#", "data_type": "DECIMAL(5,0)"},
        {"name": "THPDAT", "data_type": "DECIMAL(7,0)"},
        {"name": "THPLGP", "data_type": "STRING"},
        {"name": "THPLIN", "data_type": "STRING"}
    ]
) }}