{% set container_value = var('container') %}
{% set storage_account_value = var('storage_account') %}
{% set bootstrap_storage_location = var('bootstrap_storage_location') %}
{% set incremental_storage_location = var('incremental_storage_location') %}

{{ load_data_with_metadata(
    historical_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ bootstrap_storage_location ~"/aufk.parquet",
    incremental_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_storage_location ~"/aufk/",
    all_columns=[
		{"name": "mandt", "data_type": "STRING"},
		{"name": "aufnr", "data_type": "STRING"},
		{"name": "auart", "data_type": "STRING"},
		{"name": "autyp", "data_type": "STRING"},
		{"name": "refnr", "data_type": "STRING"},
		{"name": "ernam", "data_type": "STRING"},
		{"name": "erdat", "data_type": "STRING"},
		{"name": "aenam", "data_type": "STRING"},
		{"name": "aedat", "data_type": "STRING"},
		{"name": "ktext", "data_type": "STRING"},
		{"name": "ltext", "data_type": "STRING"},
		{"name": "bukrs", "data_type": "STRING"},
		{"name": "werks", "data_type": "STRING"},
		{"name": "gsber", "data_type": "STRING"},
		{"name": "kokrs", "data_type": "STRING"},
		{"name": "cckey", "data_type": "STRING"},
		{"name": "kostv", "data_type": "STRING"},
		{"name": "stort", "data_type": "STRING"},
		{"name": "sowrk", "data_type": "STRING"},
		{"name": "astkz", "data_type": "STRING"},
		{"name": "waers", "data_type": "STRING"},
		{"name": "astnr", "data_type": "STRING"},
		{"name": "stdat", "data_type": "STRING"},
		{"name": "estnr", "data_type": "STRING"},
		{"name": "phas0", "data_type": "STRING"},
		{"name": "phas1", "data_type": "STRING"},
		{"name": "phas2", "data_type": "STRING"},
		{"name": "phas3", "data_type": "STRING"},
		{"name": "pdat1", "data_type": "STRING"},
		{"name": "pdat2", "data_type": "STRING"},
		{"name": "pdat3", "data_type": "STRING"},
		{"name": "idat1", "data_type": "STRING"},
		{"name": "idat2", "data_type": "STRING"},
		{"name": "idat3", "data_type": "STRING"},
		{"name": "objid", "data_type": "STRING"},
		{"name": "vogrp", "data_type": "STRING"},
		{"name": "loekz", "data_type": "STRING"},
		{"name": "plgkz", "data_type": "STRING"},
		{"name": "kvewe", "data_type": "STRING"},
		{"name": "kappl", "data_type": "STRING"},
		{"name": "kalsm", "data_type": "STRING"},
		{"name": "zschl", "data_type": "STRING"},
		{"name": "abkrs", "data_type": "STRING"},
		{"name": "kstar", "data_type": "STRING"},
		{"name": "kostl", "data_type": "STRING"},
		{"name": "saknr", "data_type": "STRING"},
		{"name": "setnm", "data_type": "STRING"},
		{"name": "cycle", "data_type": "STRING"},
		{"name": "sdate", "data_type": "STRING"},
		{"name": "seqnr", "data_type": "STRING"},
		{"name": "user0", "data_type": "STRING"},
		{"name": "user1", "data_type": "STRING"},
		{"name": "user2", "data_type": "STRING"},
		{"name": "user3", "data_type": "STRING"},
		{"name": "user4", "data_type": "DECIMAL(13,3)"},
		{"name": "user5", "data_type": "STRING"},
		{"name": "user6", "data_type": "STRING"},
		{"name": "user7", "data_type": "STRING"},
		{"name": "user8", "data_type": "STRING"},
		{"name": "user9", "data_type": "STRING"},
		{"name": "objnr", "data_type": "STRING"},
		{"name": "prctr", "data_type": "STRING"},
		{"name": "pspel", "data_type": "STRING"},
		{"name": "awsls", "data_type": "STRING"},
		{"name": "abgsl", "data_type": "STRING"},
		{"name": "txjcd", "data_type": "STRING"},
		{"name": "func_area", "data_type": "STRING"},
		{"name": "scope", "data_type": "STRING"},
		{"name": "plint", "data_type": "STRING"},
		{"name": "kdauf", "data_type": "STRING"},
		{"name": "kdpos", "data_type": "STRING"},
		{"name": "aufex", "data_type": "STRING"},
		{"name": "ivpro", "data_type": "STRING"},
		{"name": "logsystem", "data_type": "STRING"},
		{"name": "flg_mltps", "data_type": "STRING"},
		{"name": "abukr", "data_type": "STRING"},
		{"name": "akstl", "data_type": "STRING"},
		{"name": "sizecl", "data_type": "STRING"},
		{"name": "izwek", "data_type": "STRING"},
		{"name": "umwkz", "data_type": "STRING"},
		{"name": "kstempf", "data_type": "STRING"},
		{"name": "zschm", "data_type": "STRING"},
		{"name": "pkosa", "data_type": "STRING"},
		{"name": "anfaufnr", "data_type": "STRING"},
		{"name": "procnr", "data_type": "STRING"},
		{"name": "proty", "data_type": "STRING"},
		{"name": "rsord", "data_type": "STRING"},
		{"name": "bemot", "data_type": "STRING"},
		{"name": "adrnra", "data_type": "STRING"},
		{"name": "erfzeit", "data_type": "STRING"},
		{"name": "aezeit", "data_type": "STRING"},
		{"name": "cstg_vrnt", "data_type": "STRING"},
		{"name": "costestnr", "data_type": "STRING"},
		{"name": "veraa_user", "data_type": "STRING"},
		{"name": "vname", "data_type": "STRING"},
		{"name": "recid", "data_type": "STRING"},
		{"name": "etype", "data_type": "STRING"},
		{"name": "otype", "data_type": "STRING"},
		{"name": "jv_jibcl", "data_type": "STRING"},
		{"name": "jv_jibsa", "data_type": "STRING"},
		{"name": "jv_oco", "data_type": "STRING"},
		{"name": "cum_indcu", "data_type": "STRING"},
		{"name": "cum_cmnum", "data_type": "STRING"},
		{"name": "cum_auest", "data_type": "STRING"},
		{"name": "cum_desnum", "data_type": "STRING"},
		{"name": "mrss_pl_stru_id", "data_type": "STRING"},
		{"name": "mrss_pl_man_typ", "data_type": "STRING"},
		{"name": "mrss_order_prob", "data_type": "STRING"},
		{"name": "mrss_act_type", "data_type": "STRING"},
		{"name": "mrss_init_done", "data_type": "STRING"},
		{"name": "mrss_datachange", "data_type": "STRING"},
		{"name": "mrss_sales_org", "data_type": "STRING"},
		{"name": "mrssnw_booked", "data_type": "STRING"},
		{"name": "vaplz", "data_type": "STRING"},
		{"name": "wawrk", "data_type": "STRING"},
		{"name": "ferc_ind", "data_type": "STRING"},
		{"name": "claim_control", "data_type": "STRING"},
		{"name": "update_needed", "data_type": "STRING"},
		{"name": "update_control", "data_type": "STRING"},
		{"name": "tas_rp_change_date", "data_type": "TIMESTAMP"},
		{"name": "tas_rp_opcode", "data_type": "INT"}
    ],
    composite_keys=["mandt","aufnr"],
    transformation_column="tas_rp_opcode",
    transformation_map={"D": 0, "I": 1, "U": 2}
) }}
