{% set container_value = var('container') %}
{% set storage_account_value = var('storage_account') %}
{% set bootstrap_storage_location = var('bootstrap_storage_location') %}
{% set incremental_storage_location = var('incremental_storage_location') %}

{{ load_data_with_metadata(
    historical_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ bootstrap_storage_location ~"/cabn.parquet",
    incremental_source="abfss://" ~ container_value ~ "@" ~ storage_account_value ~ ".dfs.core.windows.net/" ~ incremental_storage_location ~"/cabn/",
    all_columns=[
		{"name": "mandt", "data_type": "STRING"},
		{"name": "atinn", "data_type": "STRING"},
		{"name": "adzhl", "data_type": "STRING"},
		{"name": "atnam", "data_type": "STRING"},
		{"name": "atidn", "data_type": "STRING"},
		{"name": "atfor", "data_type": "STRING"},
		{"name": "anzst", "data_type": "SMALLINT"},
		{"name": "anzdz", "data_type": "SMALLINT"},
		{"name": "atvor", "data_type": "STRING"},
		{"name": "atsch", "data_type": "STRING"},
		{"name": "atkle", "data_type": "STRING"},
		{"name": "atkon", "data_type": "STRING"},
		{"name": "atend", "data_type": "STRING"},
		{"name": "ataen", "data_type": "STRING"},
		{"name": "atkla", "data_type": "STRING"},
		{"name": "aterf", "data_type": "STRING"},
		{"name": "atein", "data_type": "STRING"},
		{"name": "atame", "data_type": "STRING"},
		{"name": "atwme", "data_type": "STRING"},
		{"name": "msehi", "data_type": "STRING"},
		{"name": "atdim", "data_type": "SMALLINT"},
		{"name": "atglo", "data_type": "STRING"},
		{"name": "atgla", "data_type": "STRING"},
		{"name": "atint", "data_type": "STRING"},
		{"name": "atuns", "data_type": "STRING"},
		{"name": "atson", "data_type": "STRING"},
		{"name": "attab", "data_type": "STRING"},
		{"name": "atfel", "data_type": "STRING"},
		{"name": "attei", "data_type": "STRING"},
		{"name": "atprt", "data_type": "STRING"},
		{"name": "atprr", "data_type": "STRING"},
		{"name": "atprf", "data_type": "STRING"},
		{"name": "atwrd", "data_type": "STRING"},
		{"name": "atfod", "data_type": "STRING"},
		{"name": "athie", "data_type": "STRING"},
		{"name": "atdex", "data_type": "STRING"},
		{"name": "atfga", "data_type": "STRING"},
		{"name": "atvsc", "data_type": "STRING"},
		{"name": "aname", "data_type": "STRING"},
		{"name": "adatu", "data_type": "STRING"},
		{"name": "vname", "data_type": "STRING"},
		{"name": "vdatu", "data_type": "STRING"},
		{"name": "atxac", "data_type": "STRING"},
		{"name": "atyac", "data_type": "STRING"},
		{"name": "atmst", "data_type": "STRING"},
		{"name": "atwso", "data_type": "STRING"},
		{"name": "atbso", "data_type": "STRING"},
		{"name": "datuv", "data_type": "STRING"},
		{"name": "techv", "data_type": "STRING"},
		{"name": "aennr", "data_type": "STRING"},
		{"name": "lkenz", "data_type": "STRING"},
		{"name": "atwri", "data_type": "STRING"},
		{"name": "dokar", "data_type": "STRING"},
		{"name": "doknr", "data_type": "STRING"},
		{"name": "dokvr", "data_type": "STRING"},
		{"name": "doktl", "data_type": "STRING"},
		{"name": "knobj", "data_type": "STRING"},
		{"name": "atinp", "data_type": "STRING"},
		{"name": "atvie", "data_type": "STRING"},
		{"name": "werks", "data_type": "STRING"},
		{"name": "katalogart", "data_type": "STRING"},
		{"name": "auswahlmge", "data_type": "STRING"},
		{"name": "athka", "data_type": "STRING"},
		{"name": "athko", "data_type": "STRING"},
		{"name": "clint", "data_type": "STRING"},
		{"name": "attol", "data_type": "STRING"},
		{"name": "atzus", "data_type": "STRING"},
		{"name": "atvpl", "data_type": "STRING"},
		{"name": "atauth", "data_type": "STRING"},
		{"name": "countrygrp", "data_type": "STRING"},
		{"name": "tas_rp_change_date", "data_type": "TIMESTAMP"},
		{"name": "tas_rp_opcode", "data_type": "INT"}
    ],
    composite_keys=["mandt","atinn","adzhl"],
    transformation_column="tas_rp_opcode",
    transformation_map={"D": 0, "I": 1, "U": 2}
) }}
